### ISSUE TITLE
[macOS] Update SQLite version

### ISSUE THREAD

**Issue by jxonas** [SQLiteFlow/SQLiteFlow-Issues#108]
Awesome product! Could you please update the SQLite library to a newer version?

**Comment by SQLiteFlow** [comment]
Hello @jxonas, SQLiteFlow currently use the SQLite library that embedded in macOS/iOS, so the library can be updated through operation system update.
Which macOS/iOS version are you using?

**Comment by jxonas** [comment]
I'm on the latest version of MacOs: 10.15.5 (19F101). I have a development environment set up and already built the newest SQLite version, it's properly installed and working via the SQLite cli. Is it possible to use that same version with SQLiteFlow?

**Comment by SQLiteFlow** [comment]
I can build the latest version of SQLite library from the official source code, then embed it SQLiteFlow.app's bundle, and allow users to choose if they would like to use the SQLite library that macOS embedded or the one which is the latest version.

So yes, this feature request is accepted.

And this feature needs to take some time to make it done.  Because:
1. Since there's will be two SQLite libraries coexist in one app, looks like the change of the codebase structure won't be so tiny. 
And hopefully the change can also be allowed by the Mac App Store's App Review team.
2. Format Query, Syntax Highlighting and Code Auto Completion also need be adjusted for the latest version of SQLite library.

**Comment by SQLiteFlow** [comment]
SQLiteFlow(macOS) 4.1.0 has been released.

Now it allows user to choose the macOS embedded SQLite library or the latest SQLite library (currently SQLite 3.32.2) to work with. 

Screenshot attached.

![pic](https://user-images.githubusercontent.com/38027540/85082731-6311a180-b202-11ea-9bb1-56e72a6467bc.png)
