### ISSUE TITLE
SQLiteException: unable to open database file

### ISSUE THREAD

**Issue by doyongid** [SQLiteFlow/SQLiteFlow-Issues#128]
**Version**
 - Platform: macOS 10.15.5
 - SQLiteFlow: 4.3.1

[db.zip](https://github.com/SQLiteFlow/SQLiteFlow-Issues/files/4943866/db.zip)

Error occurs in Test2.db, and Test3.db works normally.

An error occurs when reading all test tables and loading them in the list.

I used the SQLite4Unity3d plugin in Unity 2018.4.24f1.

I created Test2.db using SQLiteFlow.

**Comment by SQLiteFlow** [comment]
Had some tests with the Test2.db you attached, looks like it can be opened successfully both in SQLiteFlow and macOS Terminal. 

Do you mean you can't open it by the SQLite4Unity3d plugin you mentioned? 
If the answer is yes, then which SQLite version is the plugin using?


Screenshot attached.

1. Opened successfully in SQLiteFlow:
![pic1](https://user-images.githubusercontent.com/38027540/87886507-43170d00-ca50-11ea-8ec9-d58ff46ac549.png)

2. Opened successfully in macOS Terminal:
![pic2](https://user-images.githubusercontent.com/38027540/87886513-49a58480-ca50-11ea-9c57-442a6aa9ecba.png)

**Comment by doyongid** [comment]
[](https://github.com/robertohuertasm/SQLite4Unity3d)
I am not sure what version the plugin uses. I also confirmed that it works on Mac.

I've used SQLiteFlow for Android app development so far, and there was no problem. However, a few days ago, I found that the db could not be read properly.
I also get the same phenomenon when I made and tested an android apk.
It worked fine before, but suddenly an error occurred.
SQLiteFlow was updated a few days ago, and I wanted to know if it was the cause.


I am going to look for other causes. I will return the review's rating.
Thank you.

**Comment by doyongid** [comment]
There is one unusual phenomenon.
When opening Test2.db in SQLiteFlow, db-shm and db-wal files are created.
This is a phenomenon that does not occur in Test3.db.

**Comment by SQLiteFlow** [comment]
> I am not sure what version the plugin uses

You can run the SQL `SELECT sqlite_version();` to check what version the plugin uses.

> When opening Test2.db in SQLiteFlow, db-shm and db-wal files are created.

This is what happens when SQLite database is configured to use WAL journal mode, you can visit this page to get more information about the WAL journal mode: https://www.sqlite.org/wal.html.

The WAL journal mode was introduced 10 years ago with SQLite version version `3.7.0` (2010-07-21), and is being used very widely in so many apps today.

Begin with SQLiteFlow(macOS) 4.3.0, a new created database is default set to use WAL journal mode. 
And of course if you prefer to use the legacy one (DELETE journal mode), you can choose it when creating a new database. Screenshots attached.

If the SQLite version that the plugin uses is lower than SQLite `3.7.0` (2010-07-21),, that's probably the reason that cause you see `'unable to open database file'` error.
If my check is right, the version of  SQLite library in SQLite4Unity3d/Plugins/x64/sqlite3.dll is `3.6.23.1` which is lower than `3.7.0`.

It's recommended that you could update the SQLite library to a newer version to use if you don't have any specific reason that have to use this very old version of it. 
But if you have to, you can change your database's journal mode to `DELETE` by run the SQL `PRAGMA journal_mode = DELETE`, you can check this link to see more about `PRAGMA journal_mode`: https://www.sqlite.org/pragma.html#pragma_journal_mode.

![pic1](https://user-images.githubusercontent.com/38027540/87989965-9901b880-cb15-11ea-85e9-9b6f8fc5ee50.png)
![pic2](https://user-images.githubusercontent.com/38027540/87989976-9ef79980-cb15-11ea-96c4-fc39f427a0e1.png)

**Comment by SQLiteFlow** [comment]
Hello @doyongid, does my answer work for your side?

**Comment by SQLiteFlow** [comment]
Close this issue for now. 
If this is still an issue, you are welcome to add comments here.
