### ISSUE TITLE
Can’t get into it 

### ISSUE THREAD

**Issue by chuy336** [SQLiteFlow/SQLiteFlow-Issues#129]
I try to open the app and it says get free trail I click it but it’s just loading long

**Comment by chuy336** [comment]
![592C3207-A2B3-4EBC-9EC0-4AD138A8639A](https://user-images.githubusercontent.com/68596299/88054954-32d46000-cb2c-11ea-905c-e8dbf30dbf61.png)

**Comment by SQLiteFlow** [comment]
When it's loading, it's communicating with iOS's App Store server, normally the process will finished in seconds. 
However, if the server has some glitch, the process maybe a litter longer, like 10~15 seconds.

If it's loading more than 20 seconds, will try to quit the app and try again work?

**Comment by SQLiteFlow** [comment]
Hello @chuy336, do you still have this issue?

**Comment by chuy336** [comment]
Still not working

**Comment by SQLiteFlow** [comment]
@chuy336 
I checked App Store Connect at my side, looks like there're numbers of users got the free trial in-app purchase in the recent 24 hours successfully.
So it's probably not an app issue.

Could you answer me some questions so I can get more sense to help you locate where the issue is? 
Since the free trial in SQLiteFlow in just a common in-app purchase, so all question below are about it.

1. Does the in-app purchase will work if you change a network environment? 
2. Does the in-app purchase will work if you restart your phone?
3. Does in-app purchase in other apps works for you?

**Comment by chuy336** [comment]
It’s probably because I’m jailbroken

**Comment by SQLiteFlow** [comment]
@chuy336 
Emm...That make sense. Jailbreak may break the stability of iOS.
My guess is if you can't get the free trial in-app purchase in SQLiteFlow in this device,
you probably can't get any in-app purchase in the apps that from App Store. And this
is just my guess.
And if the issue is because of jailbreak and in-app purchase in all apps is not working,
maybe it's more appropriate to ask the jailbreak provider side for a help, since it's not
an issue of the app itself.

**Comment by chuy336** [comment]
10-4 soldier

**Comment by chuy336** [comment]
It worked it was the jailbreak thank you

**Comment by SQLiteFlow** [comment]
@chuy336 
You are welcome.
