### ISSUE TITLE
[iOS] Supports recognize SQLite databases with custom extensions if they can appear in Browse.

### ISSUE THREAD

**Issue by jheddings** [SQLiteFlow/SQLiteFlow-Issues#130]
Platform: iOS
Version: 4.3.4

I'm unable to open databases with custom extensions, which I use as the app extension for files.  The macOS version has a work around, but I'm unable to find anything for the iOS client.  Is there a way to override and open all files?  Or perhaps a way in app to configure "known" database extensions?

Thanks!

**Comment by SQLiteFlow** [comment]
What's your database extension? 
And what's your usage case? Like you open your database through 'External Files' or 'Import Files' ?

**Comment by jheddings** [comment]
Thanks for the quick reply!

I’m using external files through iCloud.  The extension is mydb to automatically open using a specific app as opposed to the database editor.

-jh

**Comment by SQLiteFlow** [comment]
Okay, I see. 

And I would like to mention some background information first.
1. There's a little different between the relate APIs that the macOS provided and the iOS provided.
When open/import files from a file picker (this is not your case, your case is open an external folder from a file picker), in macOS, allow select all file type is allowed; in iOS, only app developer specific file type is allowed to select, which mean in that case, the file type that allowed to select is not configurable by user, it needs be pre-configured by the app developer.
The SQLite database file extensions that currently supported by SQLiteFlow(iOS) are: `.sqlite`, `.sqlite3`, `.db`, `.db3`.

2. When open an external folder from a file picker in iOS (your case), SQLiteFlow will has permission to access all files in that folder, which means open SQLite databases that have custom extensions is possible. Maybe by checking a file's magic header to see if it's actually a SQLite database file if it's has file extensions that contains text `db` or text `sqlite`.

So in iOS, let user configure "known" database extensions will not working on scenario 1 that I mentioned above. It will working on scenario 2 though. So it's probably not a good idea to implement it like that, since it working on  scenario2 but not on scenario 1 would bring a lot confusion to user.

And I'm okay to add more supported SQLite database file extensions if the extensions are generic or common to use on a SQLite database file, but in this case, `.mydb` doesn't look like widely used in the industry nowadays, I may wrong though.

So in case there's actually a possibility that you want your database file has a generic file extension, I would like to ask a question that are the four supported SQLite database file extensions looks good to you? 

And if the answer is no, then does the solution I mentioned in scenario 2 looks good to you?

**Comment by jheddings** [comment]
I agree that you should not add .mydb as recognized by SQLiteFlow, since it is not a standard extension.

If it is possible to add detection for external files, that would be great!  Otherwise, my work around is to rename the file when I want to open the database directly and rename it back when I want to open in my custom app.

Thanks for the quick responses!

-jh

**Comment by SQLiteFlow** [comment]
You're welcome.
The work around doesn't look like very convenient, so I will do the enhancement.

**Comment by SQLiteFlow** [comment]
Finished.

**Comment by SQLiteFlow** [comment]
SQLiteFlow(iOS) 4.3.5 has been released.

**Comment by jheddings** [comment]
This is working perfectly!  Thank you for the quick response!

-jh

**Comment by SQLiteFlow** [comment]
You are welcome!
