### ISSUE TITLE
Comment on your ALTER TABLE procedure

### ISSUE THREAD

**Issue by bitxianaiz** [SQLiteFlow/SQLiteFlow-Issues#136]
SQLiteFlow version 4.3.1

When viewing your ALTER TABLE SQLite code, I noticed your use of the "PRAGMA legacy_alter_table" setting. 

--Question: Why do you use "PRAGMA legacy_alter_table = ON" before ALTER_TABLE and "PRAGMA legacy_alter_table = OFF" after ALTER_TABLE, which effectively forces the ALTER TABLE process to use the (old) legacy ALTER TABLE behavior? 
Shouldn't the "PRAGMA legacy_alter_table" value be instead set to OFF before an ALTER TABLE procedure to avoid using the (old) legacy behavior?
- https://www.sqlite.org/lang_altertable.html
- https://www.sqlite.org/pragma.html#pragma_legacy_alter_table
![SQLiteFlow | Alter Table Procedure | 1](https://user-images.githubusercontent.com/64098128/89130154-abde9a80-d4d0-11ea-98a5-e842350bd6b3.png)

--Question: Is there a reason why you use the "PRAGMA legacy_alter_table" inside the BEGIN ... COMMIT code rather than outside BEGIN ... COMMIT?
![SQLiteFlow | Alter Table Procedure | 2](https://user-images.githubusercontent.com/64098128/89130160-b7ca5c80-d4d0-11ea-943d-4e79cb85692f.png)

--Feature: IMO, it would be nice if your App settings, under "Preferences... > General", would allow users to globally set the PRAGMA legacy_alter_table = ON/OFF.

Best regards,

**Comment by SQLiteFlow** [comment]
Good questions.

> Why do you use "PRAGMA legacy_alter_table = ON" before ALTER_TABLE and "PRAGMA legacy_alter_table = OFF" after ALTER_TABLE, which effectively forces the ALTER TABLE process to use the (old) legacy ALTER TABLE behavior?
> 
> Is there a reason why you use the "PRAGMA legacy_alter_table" inside the BEGIN ... COMMIT code rather than outside BEGIN ... COMMIT?

It’s because we only need the ON behavior in the "ALTER TABLE xxx RENAME TO" statement.


> Shouldn't the "PRAGMA legacy_alter_table" value be instead set to OFF before an ALTER TABLE procedure to avoid using the (old) legacy behavior?

I have the same question when I was learning how to do alter table thing with SQLite.

Like, there’s a new alter table behavior out there, why there’s still needed to use the legacy one, doesn’t the legacy one should be the one that should avoid to use anymore in future (if compatibility issue is not in concern)?

I change my thought after reading a post at SQLite forum.
https://sqlite.org/forum/forumpost/4357902333

> Well, there is actually a quite simply way of thinking about pragma legacy_alter_table.
> 
> The original (or legacy_alter_table=1) method did not assume or require that the database schema is internally consistent before making a change, and did not require it to be consistent after the change was made. It simply processes alter table commands verbatim, with no attempt to maintain consistency or coherence or integrity of the database.
> 
> The new (or legacy_alter_table=0) method assumes and (sometimes) requires that the database schema is internally consistent before making a change; and requires that the database schema is internally consistent after having made the change. It does this my making all the necessary changes to the schema to transform it from the before the command is executed assumed consistent state to the after the command is executed consistent state, such as renaming columns/indexes/constraints/views/triggers as necessary wherever they may be found (and if something is being missed that is a bug and should be reported so Richard can find and fix it). If the database schema is inconsistent before the change or would be inconsistent after the change, then an error is thrown. (though not all inconsistencies before the change are errors).
> 
> Note that this sometimes precludes being able to use a legacy_alter_table=0 alter table command to change the database from an inconsistent state to a consistent one. In such a case one must use legacy_alter_table=1.
> 
> Or for short, legacy_alter_table=1 means do as you are told, only what you are told, exactly as you are told; whereas legacy_alter_table=0 applies the transformation requested on an assumed consistent schema and results in a consistent schema, so its use on an inconsistent schema may be an error.
> 

The quote above will make me easier to explain why set legacy_alter_table to ON in the "ALTER TABLE xxx RENAME TO" statement.

That is because the "Drop Table xxx;" statement right before it may break the internally consistent of the database schema. For example, if you have a View that have a reference to table "xxx", then after execute "Drop Table xxx;", the View still exists, and the database schema will be considered in a inconsistent state, and that will make "ALTER TABLE xxx RENAME TO" statement failed if legacy_alter_table is set to OFF.

And if you want to test the behavior in the example above, you may need to set the SQLite library in SQLiteFlow's Preference to the latest one (currently SQLite 3.32.3), not the default macOS embedded one.
That is because if you use the macOS embedded one, you will always get the legacy alter table behavior set to ON if you not explicit set it to OFF. https://github.com/SQLiteFlow/SQLiteFlow-Issues/issues/99#issuecomment-631845577

**Comment by bitxianaiz** [comment]
Unfortunately, using the (old) legacy "PRAGMA legacy_alter_table = ON" is not the proper way to proceed forward. 

Instead, using the new and improved SQLite "PRAGMA legacy_alter_table = OFF" value will correctly propagate the ALTER TABLE changes to views, constraints, foreign keys, pretty much the same way it works on the larger SQL databases management systems.

The reason why the SQLite developers introduced the new "PRAGMA legacy_alter_table = OFF" in SQLite version 3.25.0 and later expanded its functionality in version 3.26.0 was precisely to replace the old legacy ALTER TABLE arguably buggy functionality.

**Comment by SQLiteFlow** [comment]
@bitxianaiz 
Yes, I know this is what the SQLite document mentioned.
But looks like currently SQLite is not in a state that is ready to totally leave off the legacy alter table behavior.

For example, if you leave the legacy_alter_table=ON, the follow SQL will produce an error ` "error in view TestView: no such table: main.Test"`

```
CREATE TABLE Test (
    id INTEGER PRIMARY KEY
)
;
 
CREATE TABLE New_Test (
    id INTEGER PRIMARY KEY
)
;
 
CREATE VIEW TestView AS
SELECT
    Test.id
FROM Test
;

DROP TABLE Test;
ALTER TABLE New_Test RENAME TO Test;

```

**Comment by SQLiteFlow** [comment]
@bitxianaiz 
Yes, I know this is what the SQLite document mentioned.
But looks like currently SQLite is not in a state that is ready to totally leave off the legacy alter table behavior.

For example, if you use the modern behavior(legacy_alter_table=OFF), the follow SQL will produce an error ` "error in view TestView: no such table: main.Test"`

```
CREATE TABLE Test (
    id INTEGER PRIMARY KEY
)
;
 
CREATE TABLE New_Test (
    id INTEGER PRIMARY KEY
)
;
 
CREATE VIEW TestView AS
SELECT
    Test.id
FROM Test
;

DROP TABLE Test;
ALTER TABLE New_Test RENAME TO Test;

```

**Comment by bitxianaiz** [comment]
Thank you for your reply. This is a very interesting subject and I totally see your point.

However, what happens is that the sample code you provided is not the typical case for "ALTER TABLE/RENAME TO" workflow and IMO not the point for the modern "PRAGMA legacy_alter_table = OFF", or what the "PRAGMA legacy_alter_table = OFF" intended to improve.

The way I see it... The idea for the "PRAGMA legacy_alter_table = OFF" is simply to properly handle the "ALTER TABLE/RENAME TO" workflow, as seen in the code and screenshot below:

```
PRAGMA legacy_alter_table = OFF;
BEGIN;
CREATE TABLE Test (
    id INTEGER PRIMARY KEY
);
CREATE VIEW TestView AS
SELECT
    Test.id
FROM Test;
ALTER TABLE Test RENAME TO New_Test;
COMMIT;
```

![Screen Shot 2020-08-03 at 8 53 55 AM](https://user-images.githubusercontent.com/64098128/89186108-586c5b00-d569-11ea-86b2-2680460e199d.png)

Running the above code to rename an SQLite table (using the modern "PRAGMA legacy_alter_table = OFF") will properly disseminate the new table name and thus will properly modify the related Views, as seen in the screenshot below:

![Screen Shot 2020-08-03 at 8 55 00 AM](https://user-images.githubusercontent.com/64098128/89187209-f876b400-d56a-11ea-8409-581cd5a6d07b.png)

In contrast, renaming an SQLIte table using the old legacy "PRAGMA legacy_alter_table = ON;" will NOT properly disseminate the new table name and thus will NOT properly modify the related Views, as seen in the screenshot below:

![Screen Shot 2020-08-03 at 9 37 04 AM](https://user-images.githubusercontent.com/64098128/89188699-00cfee80-d56d-11ea-8178-26ad295a982b.png)

Best reagards.

**Comment by SQLiteFlow** [comment]
Thank you for the reply and I get your point too.
The modern behavior of alter table is great when you only do the 'RENAME' operation. The benefits have already been mentioned in your previous posts.

However if you following the 12 steps in https://www.sqlite.org/lang_altertable.html to make schema changes, the benefits of the modern alter table behavior will be decreased nearly to 0, because 1) the original table name will not be changed in the net result and 2) `'RENAME COLUMN'` is not be used at all too.

And more importantly, I attached a screenshot, the screenshot is from you initial post. It explicitly use the modern behavior of alter table. Then there will be an SQL error at line 27 `ALTER TABLE _my_table_new RENAME TO my_table;` if you have a View that contains a reference to `my_table`. 
And this is also the reason that SQLiteFlow explicitly turn the legacy alter table to ON there before line 27.
![pic](https://user-images.githubusercontent.com/38027540/89191967-4379e100-d5d6-11ea-94a4-be40276c05b9.png)

**Comment by bitxianaiz** [comment]
The SQLite _"PRAGMA legacy_alter_table = OFF"_ functionality was introduced to safely and correctly execute the three ALTER TABLE commands currently allowed in SQLite:

```
1. To rename a table, 
2. To rename a column within a table, 
3. To add a new column to an existing table.
```

In the case you describe above, which is the "extended" steps to safely alter all aspects of an SQLite table, as implemented by SQLiteFlow, I agree with you that it is safer to run the _"PRAGMA legacy_alter_table = ON"_ statement before executing the _"ALTER TABLE ... RENAME TO ..."_ command to avoid error messages like _"error in view my_view: no such table: main.table"_.

Thank you for a good SQLite discussion and keep up the good work!

**Comment by SQLiteFlow** [comment]
You are welcome!
