### ISSUE TITLE
Password Protection of a Database

### ISSUE THREAD

**Issue by davidkirby007** [SQLiteFlow/SQLiteFlow-Issues#14]
Thank you for acting on my last suggestion,  I have now specified SQLiteFlow for a number of Diploma Courses I am writing for various Universities Worldwide.  Data Protection is obviously an important topic and whilst there are many ways of protecting data, it occurs to me that some form of password protecting a database within SQLiteFlow would be a nice feature?

**Comment by SQLiteFlow** [comment]
Hello @davidkirby007, thanks for the suggestion.
Since supporting encryption need a custom build of SQLite lib, and there are many different branches of SQLite lib that announce they support encryption, that is great.
But it will be a big mess to let SQLiteFlow supports them all. 
However if only let SQLiteFlow supports one of them, issues like database that encrypted by SQLiteFlow can't be decrypted by other clients, or database that encrypted by other clients can't be decrypted by SQLiteFlow will come out, that lead to this feature only useful to several people who use similar custom build of SQLite lib as SQLiteFlow does. It don't feel right.
So until an elegant solution appears, this feature may not be implemented, please don't hate me...

**Comment by SQLiteFlow** [comment]
Close for now. Might reopen in some day.
