### ISSUE TITLE
Thanks for Version 4.5.0 + Some Observations

### ISSUE THREAD

**Issue by bitxianaiz** [SQLiteFlow/SQLiteFlow-Issues#140]
Thanks for your 4.5.0 upgrade.

Observations, following Apple's old _"Strive for Excellence"_ mantra. Three categories:

**--GUI BUG: Right gutter space missing.**
![right gutter space missing](https://user-images.githubusercontent.com/64098128/91594612-2cf24b80-e930-11ea-8acb-598de16c2362.png)

**--Code and GUI Semantics: Case consistency and wording.**
![semantics | case consistency](https://user-images.githubusercontent.com/64098128/91597329-0f72b100-e933-11ea-940d-a605c54f704e.png)

![semantics | case consistency 2](https://user-images.githubusercontent.com/64098128/91597605-20232700-e933-11ea-84c9-6c07fbede002.png)

![semantics | case consistency 3](https://user-images.githubusercontent.com/64098128/91597882-316c3380-e933-11ea-95e2-b8dee3e48024.png)

**--Mac GUI: Frequently used objects | Show-hide sidebar.**
![show-hide sidebar](https://user-images.githubusercontent.com/64098128/91598673-6f695780-e933-11ea-8a7c-b99152e19353.png)

Best regards.

**Comment by SQLiteFlow** [comment]
Thank you for the feedback.

1. GUI BUG: Right gutter space missing.
Fixed in SQLiteFlow(macOS) 4.5.1, will release it soon.

2. In SQLiteFlow(macOS) 4.5.1, changed the text "`When Delete a Temporary Query:` ",  "`Put It to "Recent Temporary Queries"` the more proper one that you mentioned.

3. About the on/off words in Table Schema or Query Editor.
I admit it's a weird case. The queries you saw in Table Schema was pre-formatted by Format Query.
The reason the word "`on`" is set to upper case is because "`on`" is a member of SQLite's keyword (https://www.sqlite.org/lang_keywords.html), and Preference - Format Query - Keyword Style is set to "Upper Case". 
And the reason that the word "`off`" is not set to upper case is "`off`" is not a member of SQLite's keyword.
I will think a way to handle this issue in future version. Maybe by treating "`off`" also a keyword, as a special case.

4. About the on/off words in Preference - General.
I think it's probably better to leave it that way, since they are not in a query, and it's weird to let the case style there be controlled by Format Query - Keyword Style.

5. Mac GUI: Frequently used objects | Show-hide sidebar.
It's already there in version 4.5.0. 
To enable it, right click the Toolbar - Customize Toolbar..., then drag the "Sidebar" item to the Toolbar.
Screenshots attached.

![pic1](https://user-images.githubusercontent.com/38027540/91625800-cd9e4500-e9dc-11ea-9ddc-26bd14bb6a73.png)
![pic2](https://user-images.githubusercontent.com/38027540/91625797-c9722780-e9dc-11ea-912c-7d538e2ba81a.png)

**Comment by SQLiteFlow** [comment]
SQLiteFlow(macOS) 4.5.1 has been released.
