### ISSUE TITLE
Preferences > Format Query settings not being applied to the SQL query editor's Format Query

### ISSUE THREAD

**Issue by bitxianaiz** [SQLiteFlow/SQLiteFlow-Issues#146]
**Version**
 - Platform: macOS 10.15.7
 - SQLiteFlow: 4.6.1

**Steps to Reproduce**
Set the SQLiteFlow _Preferences > Format Query_ settings to:
--Prefer Indent Using: Tabs
--Indent Width: 4 spaces
![Preferences   Format Query](https://user-images.githubusercontent.com/64098128/95451305-99039e80-0935-11eb-8981-2126a7088ff7.png)
**Expected behavior**
The expected behavior is for the SQL editor to use the SQLiteFlow _Preferences > Format Query_ settings:
--Prefer Indent Using: Tabs
--Indent Width: 4 spaces

Instead, the SQL editor's _Format Query_ implementation ignores the _Preferences > Format Query_ settings. It uses a combination of Tabs and Spaces.
![Format Query copy](https://user-images.githubusercontent.com/64098128/95451837-5e4e3600-0936-11eb-80c0-fd4147bf90d2.png)

**Comment by SQLiteFlow** [comment]
Sorry for the late response.

I think there're two topics.

One is, which works as expected:
In the setting of Format Query, select Prefer Indent Using Tabs may still result in spaces, if the tab width and the total indent width don't match.

Another one is, which I'm not sure if it's a thing that needs to be change:
Subquery has an hard coded indent which is 2 relate to the `(` character.

**Comment by SQLiteFlow** [comment]
And what's your opinion?

**Comment by bitxianaiz** [comment]
My opinion is that clicking the _"Format Query"_ button should format the query based on the application's _SQLiteFlow > Preferences > Format Query_ settings. Therefore, if the _SQLiteFlow > Preferences > Format Query_ settings are...

- Prefer Indent Using: Tabs
- Indent Width: 4 spaces
- Keyword Style: Upper Case
- Comman(",") that Splits Column Definition Style: Trailing
- Semicolon(";") at the End of Query: True

...then, the resulting formatted query should follow the _SQLiteFlow > Preferences > Format Query_ settings, as shown on the screenshot below.

![Format Query](https://user-images.githubusercontent.com/64098128/96817677-d82df700-13ed-11eb-8d49-2bca91cfbb16.png)

Currently, that expected behavior is not working. The resulting formatted query ignores the _SQLiteFlow > Preferences > Format Query_ settings. It uses a combination of Size-4-Tab and Size-2-Space indents.

Therefore, if clicking the _Format Query_ button results in a query format that is different than the application's _SQLiteFlow > Preferences > Format Query_ settings, you might as well eliminate the _SQLiteFlow > Preferences > Format Query_ settings feature.

**Comment by SQLiteFlow** [comment]
I understand what you expected. In this case, you want there're 8 leading spaces, and use 2 Tabs which width is 4 to present the leading spaces.

But actually the leading spaces may be any value caused by different type of SQL, that is to say the leading spaces may not always be any of 4, 8, 12, 16...

In this case, it may be 6. And if the value is 6, the leading space will result in 1 Tab character and 2 space characters.
If the value is 15, then leading space will result in 3 Tab characters and 3 space characters.
If the value is 16, then leading space will result in 4 Tab characters.

That what I mentioned in my previous post topic 1: 
Prefer Indent Using Tabs may still result in spaces, if the tab width and the total indent width don't match.

**Comment by bitxianaiz** [comment]
I just don't really understand your explanation of how Indents work on your SQLiteFlow _Format Query_ feature with a combination of Tabs, Spaces, some size-4 and some size-2 regardless of the user preference settings. That's something I've never seen before.

Now, you asked me "And what's your opinion?" and so I volunteered my opinion strictly from the point of view of somebody who spent 27 years as a software professional focused mainly on SQL Database Apps and on Mac OS GUI design. 

In any case, this is your software, and so you can design its functionality any way you like. Would you consider adding a checkbox to Show/Hide the SQL Editor's _Format Query_ button in the _SQLiteFlow > Preferences > Format Query_ settings page?
![Screen Shot 2020-10-22 at 1 34 30 PM](https://user-images.githubusercontent.com/64098128/96909012-68f6e800-146b-11eb-8d42-4726c8c12db7.png)

Best,

**Comment by SQLiteFlow** [comment]
I appreciate your opinion. 
Maybe caused by I'm not a native English speaker, so sometime what I was saying may not sound too polite, I'm sorry for that, I wasn't mean it.

I think we both have a goal that we want make SQLiteFlow better. I really need to say thank you here.

In my opinion, I will make change (implement a feature or fix a bug) to SQLiteFlow if the changes could move this app forward reasonly if it's a feature or could really fix an issue and not bring other issue if it'a bug. Making changes should not hurry, or it may bring more issues.

Now back to our topic.

> I just don't really understand your explanation of how Indents work on your SQLiteFlow Format Query feature with a combination of Tabs, Spaces, some size-4 and some size-2 regardless of the user preference settings. That's something I've never seen before.
1. How Indents work: SQLiteFlow first calculate how many spaces that needed at the leading of a line, then, in this case, fill Tabs characters in it, if the Tab width is too long, then fill spaces characters in it.
2. The mix tab and space style is actually learned from Qt, a cross-platform software development platform.

Why SQLiteFlow choose to use the mix tab and space style when "Prefer Indent Using" set to "Tabs"?
There're two reasons:
1. Think about this simple query, please see the two pictures below. The arrow represents size-4 Tab, and the - represents space.
This first one is the current behavior, and the second one is the "all tabs" behavior. Which one do you think it looks better or tidy?
![1](https://user-images.githubusercontent.com/38027540/96943574-271d7e80-150b-11eb-972b-64bdb056149f.png)
![2](https://user-images.githubusercontent.com/38027540/96943578-28e74200-150b-11eb-8862-dc935d7e6ee9.png)
2. The visual result of the format query will be same when the setting of "Prefer Indent Using" set to either "Spaces" or "Tabs"

I'm saying all these is for explaining what it behaves like that currently, and not for rejecting potential changes.
However, changes may need enough discussions or reasons to make. As a 27 years experienced professional programer, I think it very easy for you to get that.

For me, the first picture above is a little better, this is mainly why I'm not thinking it a bug, and why I tried to explain to you how indent works in SQLiteFlow in first place.
To make changes that you proposed, maybe I need more reasons from you, since it may affect to exists users who rely on the current behavior.


> Would you consider adding a checkbox to Show/Hide the SQL Editor's Format Query button in the SQLiteFlow > Preferences > Format Query settings page?

I don't think this is an action that could move SQLiteFlow forward, I think the right way to make a feature forward is to make it better, not try to hide it, doesn't it?

**Comment by SQLiteFlow** [comment]
Close for now. This issue is welcome to be reopened at any time.
