### ISSUE TITLE
Sorting doesn't take into account numerical data

### ISSUE THREAD

**Issue by mouser** [SQLiteFlow/SQLiteFlow-Issues#153]
**Version**
 - Platform: any
 - SQLiteFlow: 4.7.0

**Steps to Reproduce**
Open any database that contains a table that has string values
Assuming objects ["Object 1" , "Object 2", ..., "Object 10"]

Sort comes out as:  ["Object 1" , "Object 10", "Object 2", ...]

**Expected behavior**
Sorted as:  ["Object 1" , "Object 2", ..., "Object 10"]

Proper sort flags should include

            return [obj2.title compare: obj1.title options: NSNumericSearch | NSCaseInsensitiveSearch | NSDiacriticInsensitiveSearch];

**Screen shots**
<img width="1500" alt="Screen Shot 2020-11-19 at 22 18 53" src="https://user-images.githubusercontent.com/2145106/99753982-737dbf00-2ab5-11eb-9304-0b2440eb23a3.png">

**Comment by SQLiteFlow** [comment]
I think the sorting behavior you mentioned is a feature in Cocoa Foundation.
The sorting behavior in SQLiteFlow is based on the "ORDER BY" clause behavior in SQLite, which is implemented by design.
Please see the screenshot, at the bottom of the app, it shows the SQL that generated the data.

<img width="1500" alt="pic" src="https://user-images.githubusercontent.com/38027540/99755376-934ccb80-2b25-11eb-9d36-d029eb6d462d.png">

**Comment by mouser** [comment]
Ah yes. I was expecting that the table was resorted by the column after the SQL ORDER BY, given the default table pulls only 1000 objects. Using CAST AS INTEGER in the column wouldn't help in this particular case because the column isn't strictly numerical but contains numerical info.
