### ISSUE TITLE
Unable to Query Local DB on iOS

### ISSUE THREAD

**Issue by ssnkhan** [SQLiteFlow/SQLiteFlow-Issues#164]
**Version**
 - Platform: iOS 14.4.2
 - SQLiteFlow 4.8.4 for iOS

**Steps to Reproduce**
1. Load/Open database in SQLiteFlow
2. Select DB
3. Select "Queries"
4. Unable to select current database in the "Recents" popover -- greyed out
5. Can't query the database as a result

**Expected behavior**
1. I should be able to open a database and write a SQL query

**Screen shots**
https://user-images.githubusercontent.com/11506722/115965816-cbb46380-a522-11eb-9d37-4f4fc333e48f.jpeg

I am currently on the 14 day trial.

**Comment by SQLiteFlow** [comment]
You needn't open a database in step 4, because you already opened a database in step 1.
I think what you need to do next is creating a SQL script file in the "Browse" tab.

Screenshot attached.
![115965816-cbb46380-a522-11eb-9d37-4f4fc333e48f](https://user-images.githubusercontent.com/38027540/115966554-b827ed80-a560-11eb-8d15-ea1c9a91a079.jpeg)

**Comment by ssnkhan** [comment]
That’s the point/bug — it’s impossible to query the database at the moment.
