### ISSUE TITLE
Suggested Features

### ISSUE THREAD

**Issue by jmstev13** [SQLiteFlow/SQLiteFlow-Issues#168]
Great product! It has proven to be a great tool so far. I do have a couple of suggestions in order of "importance", at least to me.

1. Add the fields to the tables in the tree. Add the type in the name as well. This is huge!
2. In the code editor when you go to the next line, keep the indent from the previous line.
3. Add the ability to switch to dark or light mode no matter how the system is set.

Again, thanks for the great product!

**Comment by SQLiteFlow** [comment]
Thank you for like the product.

Which platform are you in? macOS or iOS?

> Add the fields to the tables in the tree. Add the type in the name as well. This is huge!

Can I know the use case? 
And assuming you are using SQLiteFlow(macOS), do you know that you can always right click a table name, and click "Table Schema..."  to see all the detail of the structure of a table including the field type you mentioned? See screenshot.
![table schema](https://user-images.githubusercontent.com/38027540/123567920-cc54c900-d7f5-11eb-909c-ea7f7530f127.png)


> In the code editor when you go to the next line, keep the indent from the previous line.

This one is interesting, I think I will see what I can do.
Currently you can use tab key to insert indent easily. See screenshot.
![tab](https://user-images.githubusercontent.com/38027540/123567371-9236f780-d7f4-11eb-89e5-d8efb5c63dcb.png)


> Add the ability to switch to dark or light mode no matter how the system is set.

Ah, I am not sure I will implement this one. Because in my pov, if you want dark or light mode, why not just set it in system's Preferences? Or is there something I can improve to the software to let dark or light mode behave better to let you satisfied with it? 

Regards.

**Comment by jmstev13** [comment]
I am using the MacOS version currently.

I saw the right click option to see the table structure however being able to see the fields in the tree would be a great reference tool. Something similar to what Microsoft does in SQL Server Management Studio or SQLPro for SQLite does on the Mac.

The tab for the code editor is just a “nice to have”. It saves a keystroke is all. Not a huge deal.

I prefer light mode for the operating system and dark mode for some of my programming tools, like Xcode. Again, not a big deal just a nice to have.

Thank you for the fast and detailed response! Much appreciated!

**Comment by SQLiteFlow** [comment]
I see, thank you for pointing these out. I will see what I can do all three of them.
And I will keep you posted.

Regards.

**Comment by jmstev13** [comment]
Thank you!

**Comment by SQLiteFlow** [comment]
Two features has been finished for now and they are both available on App Store now.
You can update the app and see if it looks good to you, please let me know if you have further questions or advices.

One is supports manually specific light/dark appearance.
![appearance](https://user-images.githubusercontent.com/38027540/124577846-3d445280-de80-11eb-9909-b7e5a120bab5.png)

Another is supports show table fields information in database list. The information currently contains field name, field type, not null constraints and primary key constraints info.
![fields](https://user-images.githubusercontent.com/38027540/124577859-3fa6ac80-de80-11eb-914a-fdd96ca76e44.png)

**Comment by jmstev13** [comment]
Thank you! As soon as I see it come through the App Store updates, I’ll try it out!

**Comment by SQLiteFlow** [comment]
You can see the updates now through the App Store by press Cmd + R or menu - Store - Reload Page in App Store's Updates section. 😀

**Comment by jmstev13** [comment]
I didn’t know you could do that! A terrific tip! Thank you!

The update is perfect! The changes help tremendously! Thank you so much for the quick response and great product!

Now for another request, I took a look at the iPad app and I’m wondering if you can emulate the side bar that is in the Mac app in the iPad app? I’m not sure how possible that is or not.

In any event, thanks again for the updates and a terrific product!

**Comment by SQLiteFlow** [comment]
You are welcome!

And about the iPad app, the feature you mentioned is on my list long ago actually, however it's require a not quite small change, so it may takes me some time to implement it.

**Comment by jmstev13** [comment]
No problem! As long as it is on the list, I am set!

**Comment by SQLiteFlow** [comment]
SQLiteFlow(macOS) 5.2.0 has been released. 

Now it supports syntax aware indenting when typing Return. 

You can trigger this feature on/off in Preferences - Text Editing - Syntax-Aware Indenting. (The default is set to on.)

And since this is the initial version of this feature, so you if found anything behave unexpected, please let me know.

![pic](https://user-images.githubusercontent.com/38027540/126582058-5b8b343d-f342-44e7-95f4-dd0a1d867ee4.png)

**Comment by SQLiteFlow** [comment]
Update the UI at SQLiteFlow(iOS) 5.1.0

Now if you open a database on iPad, you will see a sidebar like UI.

Screenshot attached. 

And if you have any questions, please let me know.

![sidebar](https://user-images.githubusercontent.com/38027540/128103919-29589853-2a14-4e87-8d31-2cc0c2a8ee95.png)
