### ISSUE TITLE
macOS Shortcuts support

### ISSUE THREAD

**Issue by pointlessone** [SQLiteFlow/SQLiteFlow-Issues#171]
Shortcuts are coming to macOS this fall.

The shortcuts are shared between iOS and macOS but SQLiteFlow actions are only available on iOS. I wonder if the same actions could be ported to macOS for feature parity.

**Comment by SQLiteFlow** [comment]
I feel positive that the future version of SQLiteFlow(macOS) could supports Shortcuts. Actions like "Run Query" and "Import CSV" can be configured in the Shortcuts app.

But I'm not sure yet if one concrete action can be shared between SQLiteFlow(iOS) and SQLiteFlow(macOS), since SQLiteFlow(iOS) and SQLiteFlow(macOS) are literally two apps under the hood.

**Comment by SQLiteFlow** [comment]
Status update.

After some investigation, I don't think one concrete action can be shared between SQLiteFlow(iOS) and SQLiteFlow(macOS). 

This is mainly because of there's no concept of "External Folder" on macOS side, which means SQLiteFlow(macOS) will probably not able to locate the SQLite database that specified in the action that iOS side created.

So if SQLiteFlow(macOS) wants to handle an action, this action should be a new one that created on macOS side which is suitable for this platform. The upside is, I think, the action on the macOS side is more easy to created since there's less parameter to specific, like there's no need to specific an "External Folder" when user choose a database.

**Comment by pointlessone** [comment]
Is there any way to make actions portable?

For example, make a new action that accepts a db file as an input and have another action (or use the ones provided by Shortcuts) that can look that db file up in a portable manner?

**Comment by SQLiteFlow** [comment]
Hmm, it's a nice idea.
That will make the incompatible action up to "Get database" level.

In theory, this way may will work, but not sure if it will work in real world yet:
On iOS side, SQLiteFlow supports a new action "Get database", this action requires two parameters: "External Folder" and "Database".
On macOS side, SQLiteFlow supports a new action "Get database", this action only requires one parameter: "Database".
The existing two actions, "Run Query" and "Import CSV", add support to accept the result of "Get database" as a parameter.

Then user can use "Get Device Details" provided by Shortcuts to determine which "Get database" action will run.

**Comment by SQLiteFlow** [comment]
Don't think it's make things simpler compare to

var myQuery = "xxxxx;"

if "Get Device Model"  == "macOS" {
    run action "Run Query (macOS)" myQuery
}
else "Get Device Model"  == "iOS" {
    run action "Run Query (iOS)" myQuery
}

**Comment by pointlessone** [comment]
Well, that a workable workaround. Thank  you.

**Comment by SQLiteFlow** [comment]
Which one?😂

**Comment by SQLiteFlow** [comment]
Did a lot of researches these days about this feature.

Looks like there're quite a few different behaviors between iOS and macOS to prevent SQLiteFlow using an elegant way to make an action cross platform.

The confusing it bring to user is a little more than the benefits it bring to user based on my test.

So I decided to make the shortcut actions platform independent at the initial version of macOS actions. And you can use it in practice to see if it's good or not when it's released.

Two screenshots attached to show how one action can both available on both iOS and macOS using the current platform independent solution.

![Intent_Mac](https://user-images.githubusercontent.com/38027540/143001588-bfdec712-cba5-467a-b225-aa88b247c310.png)
![Intent_iOS](https://user-images.githubusercontent.com/38027540/143001594-9309da4a-d49d-4177-99d0-7e6ace1749d2.png)

**Comment by SQLiteFlow** [comment]
**The differences between macOS action and iOS action:**

1. On macOS, the action will not have the ability to download iCloud offload files because there's no file access permission. So user should make sure all related files are downloaded correctly to disk before run the action.

2. On macOS, Run Query action will not have "Save to Folder" option because there's no need to. The "Save File" action offered by Shortcut app can do this job very well both in macOS 12 and iOS 15 now.

3. On macOS, there's no "Run in App" option, it's unnecessary to have it in most situations on macOS.

**The caution that operate SQLite files which are able to sync to cloud:**

There's potential risk that the version of SQLite main database file and temp journal file mismatch during syncing to cloud process when operate SQLite database. So be careful with this situation when work with it.

**Comment by pointlessone** [comment]
Thank you for extensive explanation.

I guess this issue can be closed. Or moved to discussions for others to find.

**Comment by SQLiteFlow** [comment]
This feature has been released. 
Now “Run Query” intent and “Import CSV” intent are available in the Shortcuts app on macOS side.
