### ISSUE TITLE
Automated ios Shortcut now requires user interaction

### ISSUE THREAD

**Issue by gmrusse11** [SQLiteFlow/SQLiteFlow-Issues#175]
Hi, I am not actually sure if this is a bug or if I need to change a configuration somewhere, but I had an iOS shortcut I had automated to run hourly that would pull some data and add a record to a table in one of my SQLiteFlow databases.  This had been running without any issue, but starting this morning it required me to hit the notification on the Lock Screen before it would insert.  I believe I updated the app sometime late last night.

**Comment by gmrusse11** [comment]
I should note that this only occurs when my phone is locked.

**Comment by SQLiteFlow** [comment]
Actually it is a bug if it could run when device is locked without user interaction.

I tested on my device with several recent versions of SQLiteFlow(iOS), the bug seems not exists in these versions I tested. So I'm not sure what previous version you are using.

Since this behavior is set without too much consideration about the automation purpose you mentioned.

So in next version, I will let the app allow the two shortcuts intents "Run Query" and "Import CSV" to run when device is locked without user interaction to make it convenient for automation purpose.

Regards.

**Comment by gmrusse11** [comment]
Thanks very much!  I am pretty sure I had been running the previous version since I tend to check for app updates regularly.  Not sure why it was letting me slip past, but it has been really helpful for helping me to track history from some HomeKit sensors.

**Comment by SQLiteFlow** [comment]
You're welcome.

I will let you know when the new version of SQLiteFlow(iOS) is available on the App Store.

During my test, after you update SQLiteFlow to the coming version, you may need to restart the device to get the new behavior update, or the Shortcuts app seems like using a cached version of action to do the job.

**Comment by SQLiteFlow** [comment]
SQLiteFlow(iOS) 5.1.2 has been released, and it's available on the App Store now.

**Comment by gmrusse11** [comment]
Thank you, that was very quick :) It's working for me again.

**Comment by SQLiteFlow** [comment]
You're welcome.
