### ISSUE TITLE
SQLITE Wont start OSX Monterey 11.2

### ISSUE THREAD

**Issue by what2be** [SQLiteFlow/SQLiteFlow-Issues#187]
**Version**
 - Platform: [e.g. macOS 10.14.5]
 - SQLiteFlow: [e.g. 3.6.0]
OSX Monterey 12.1
5.6.0

**Steps to Reproduce**
Upgraded from big sur to Monterey , sqlite wont start, says it corrupted. Deleted sqliteflow and redownloaded from app store but problem persists. 

**Expected behavior**

**Screen shots**
<img width="277" alt="Screen Shot 2021-12-16 at 11 33 20 PM" src="https://user-images.githubusercontent.com/22668332/146506922-661136ef-ee27-4b2f-bd34-f9cb761c9cfe.png">

**Comment by SQLiteFlow** [comment]
I delete SQLiteFlow from my machine that running macOS 12.1, and re-download it from App Store, everything looks fine at my side.

So is there any contents at this folder on your machine?
/Applications/SQLiteFlow.app/Contents/_MASReceipt

Sometime App Store has glitch, so maybe you could try this and see if it will work:
1. Delete the app.
2. Restart your Mac.
3. Re-download it from App Store.

**Comment by what2be** [comment]
Contents of folder….




Ill try deleting and restarting and reinstalling. 

-Geoff

**Comment by SQLiteFlow** [comment]
Is the previous post contains a picture? 
If so, please adding post through Github webpage, adding post through e-mail will not attach the picture.

So what's in that folder? Is it empty or has something?

**Comment by SQLiteFlow** [comment]
Hey there, does the issue get resolved?

**Comment by what2be** [comment]
No, I deleted the receipt file in the location you referred to and then deleted the app and restarted the machine. I then downloaded it again from the appstore and tried to start it up and it gave me the same error,. (screen shot below)
I also added the app to the security preference pane giving it full disk access thinking that might have been the problem but it didnt resolve my issue. 
<img width="288" alt="Screen Shot 2021-12-17 at 4 41 35 AM" src="https://user-images.githubusercontent.com/22668332/146546298-33875dfb-ebc5-47c6-8b90-7e20f35ff9cc.png">

**Comment by SQLiteFlow** [comment]
You mean when the error dialog shows up, the location I mentioned before has the receipt file?

**Comment by what2be** [comment]
correct, I attached it to this message but I had to .zip it first. 
[receipt.zip](https://github.com/SQLiteFlow/SQLiteFlow-Issues/files/7735530/receipt.zip)

**Comment by SQLiteFlow** [comment]
Thank you. I download and check the receipt, it seem looks good.

This issue may caused by the receipt be treated as malformed file.
So may I have your mac address to debug why the receipt be treated as malformed?
You can send it to me through my e-mail: sqliteflow_AT_hotmail.com

And I deleted your previous post to in case your sensitive information leaked.

**Comment by SQLiteFlow** [comment]
And the device model info, for example, MacBook Pro (Retina, 15-inch, Mid 2017) is appreciated too.

**Comment by what2be** [comment]
Mac Pro 5,1

**Comment by SQLiteFlow** [comment]
1.
> Mac Pro 5,1

The Mac Pro (Mid 2012)? Does it really support to update to macOS 12? How do you managed to upgrade it?

2.
Thank you, I received your e-mail. And use the mac address you sent me to debug it.

Turns out the hash value of the mac address in the receipt file does not match the hash value of your machine's Mac address, then the receipt file be treated as malformed.

Normally the receipt file is App Store generate for your machine, and the hash value of the machine's Mac address in the receipt file will match the hash value of your machine's Mac address.

3. So I'm wondering is # 2's unexpected behavior is relate to the way that when you do upgrade, some unexpected changes have been made in # 1?

**Comment by what2be** [comment]
You are correct sir. When I used this Mac address 00:23:df:df:2d:b5 
It starts up just fine. Im using both the Mac pro’s build in NIC’s in a 802.3ad virtual configuration and when I bind card 2 first instead of 1 it gives card 2’s nic. If I bind card 1 first instead of 2 it gives card 1’s nic. 

It is indeed a Mac Pro 5,1, I use dortania open core legacy patcher from GitHub.  Great team of people work on this project. Highly recommended. 

https://dortania.github.io <https://dortania.github.io/>

Thanks again for all the help Have a great day. 

Geoff Brandon

**Comment by SQLiteFlow** [comment]
You mean you can launch SQLiteFlow successfully now after you tweaked the network cards thing?

Oh, I see how you upgraded it to macOS 12, thanks.

**Comment by what2be** [comment]
Yes I simply changed the binding order but if I would’ve never created a virtual connection to combine the two cards it would’ve worked right from the start. 

-Geoff

**Comment by SQLiteFlow** [comment]
Okay, sounds interesting. And congrats!

You're welcome to ask me more questions if you think I may can help in future. :)
