### ISSUE TITLE
Import multiple Files at once

### ISSUE THREAD

**Issue by 12komma5** [SQLiteFlow/SQLiteFlow-Issues#195]
It would save a lot of time, if the import-dialog would allow to select and thus import multiple files into an existing table at once.

**Comment by 12komma5** [comment]
macOS

**Comment by SQLiteFlow** [comment]
A good new is, if you are on Mac, you can import multiple CSV files now without an update of SQLiteFlow!

Since SQLiteFlow supports a Shortcut action: Import CSV. 

So you can achieve the goal with cooperate with Shortcuts!

A demo screenshot attached. Please let me know if you have any questions.
![DemoCSV](https://user-images.githubusercontent.com/38027540/174202516-6e847e73-59c2-44a0-a96c-55d29835bc5f.png)

**Comment by 12komma5** [comment]
Oh wow, thank you very much. This is even better! Works perfectly.

**Comment by SQLiteFlow** [comment]
You're welcome!
