### ISSUE TITLE
UUID Representation

### ISSUE THREAD

**Issue by andykent** [SQLiteFlow/SQLiteFlow-Issues#204]
Hi, first off thanks for a great App, I'm a big fan and things are working great for us. I have one feature request that I hope you will consider that would really improve our experience though.

We have tables that store UUID fields as 16 byte blobs, I think this is fairly common and the default UUID storage format for libraries like GRDB. It would be great if there was a way to have these show up in the SQLiteFlow table view as string formatted UUIDs to make it more human readable in the UI and allow for easy copy/paste etc.

I understand it's often not desirable to render blobs as strings but in this case it would make for a much nicer experience. Maybe either you could use some heuristics to decide if something is a UUID and render it as a string or if this is not possible some toggle to change the render mode.

Thanks.

<img width="581" alt="Screenshot 2023-01-26 at 11 08 20" src="https://user-images.githubusercontent.com/614/214821356-24cdac91-1e91-4ac3-9541-fec912eff0a7.png">

**Version**
 - Platform: macOS 13.2
 - SQLiteFlow: 5.9.1

**Comment by SQLiteFlow** [comment]
Sounds interesting to me.
You prefer display it as formatted UUID more or easier copy/paste as formatted UUID more?

**Comment by andykent** [comment]
I'm not 100% sure I understood your question but I would ideally like to see it in the format:

```
7deb48eb-deb5-4c7a-a24b-e1b6f6d369fb
```

or uppercase

```
7DEB48EB-DEB5-4C7A-A24B-E1B6F6D369FB
```

**Comment by andykent** [comment]
being able to see it in the UI is my main request but copy/paste support would be helpful too.

**Comment by SQLiteFlow** [comment]
> being able to see it in the UI is my main request but copy/paste support would be helpful too.

Okay, that's exactly what I'm asking.

Two pictures attached. Looks good to you?
<img width="984" alt="1" src="https://user-images.githubusercontent.com/38027540/214843034-cf732b52-1dc4-49dc-993a-f21a15053944.png">
<img width="888" alt="2" src="https://user-images.githubusercontent.com/38027540/214843063-160d7734-c185-4844-90ae-f00d70ce605e.png">

**Comment by andykent** [comment]
wow, that was quick! ❤️ 

It looks perfect and this will be an amazingly helpful addition for us.

Also, how did @groue find this issue so quickly? I didn't even link to GRDB. 😄

**Comment by groue** [comment]
😇 I sometimes search for GRDB in all GitHub issues :) I promise this is not creepy, it's just a way to discover what users are doing, and find inspiration!

**Comment by groue** [comment]
Besides, I have the same problem with UUIDs 😅

**Comment by andykent** [comment]
Not creepy at all. You are both legends and am in awe of the level of support in both projects.

Thank you again.

**Comment by SQLiteFlow** [comment]
SQLiteFlow(macOS) 5.9.2 has been released. So this feature is available on App Store now.
1. To enable this feature, go to Settings - Data Editor - enable Show 16 Bytes BLOB as UUID String.
2. In Data Editor or Query Results's table view, if a cell contains 16 bytes BLOB, then it will display a UUID string info, eg: `[UUID: 7DEB48EB-DEB5-4C7A-A24B-E1B6F6D369FB]`.
3. When click a UUID cell, a hex editor will show, and the title of the hex editor will also contains the UUID string, so you can copy it to clipboard if you like.
4. If you want to copy a UUID string, for example copy the string `7DEB48EB-DEB5-4C7A-A24B-E1B6F6D369FB` and paste it as 16 bytes BLOB then save it to the database, you can achieve this by copy the UUID string to clipboard and then paste it to the hex editor mentioned in # 3, then click "Apply".

This feature is interesting and not quite complicate to implement, that makes it quick :).
Please let me know if there're issues when you're using it, I would like to solve it.

And @groue, happy to help :).

**Comment by andykent** [comment]
Thanks so much for this amazing turn around, less than 24 hours from suggestion to in the AppStore. I am impressed.

It's a big improvement as it is and will help me a lot so thanks again.

I do have a couple of further suggestions I think would make it even better but please consider these non-urgent and totally optional improvements you could look at in the future.

1. Because of the `UUID: ` prefix the table view considers it a word boundary and so narrow columns don't truncate very nicely. Given they already show up in a different colour I actually think you could get rid of the UUID: prefix.
<img width="307" alt="Screenshot 2023-01-27 at 08 43 27" src="https://user-images.githubusercontent.com/614/215044679-371aa486-6477-4e41-8639-5d7e2a6d4b83.png">

2. It might be nice if they were displayed in a monospaced font, I think it would make them more scannable. This might also be enough of a hint that it was blob data to mean you could remove the UUID: prefix. Something like `[DB7968F0-7A03-47F8-B9E2-BC5299FCB360]`
<img width="392" alt="Screenshot 2023-01-27 at 08 46 36" src="https://user-images.githubusercontent.com/614/215045014-f7aeadb4-b685-4015-b860-c9f6a8825d48.png">

3. Editing values: it would be nice if there were an easy way to paste a string UUID into a field in the UI (I'm not sure what the UI for this would look like). FWIW In Postico you can edit UUIDs just like any other text field, although Postgres has a specific uuid column type so it's a little different. 
<img width="286" alt="Screenshot 2023-01-27 at 08 56 22" src="https://user-images.githubusercontent.com/614/215046848-ee5d8d6b-fc4d-47d6-b569-458ea3aae929.png">

Again, to be clear, please don't feel pressure to actually do these unless you agree with them, they are just friendly feedback and suggestions for future improvements to the feature.

Thanks again ❤️

**Comment by SQLiteFlow** [comment]
1. I'm cool with the removing of UUID prefix idea and use a monospaced font idea. But you may want to know that they will not lead to the UUID string truncating very nicely (a little nicer, but not very nicely) in a narrow column during my test.
2. By the way, when you reopen a data editor tab, and if you see a UUID column be truncated like the first image you attached, then it's probably a bug. The expected behavior is when you open a data editor, the column has enough space to show it.
3. To edit it inline, oh God no. As you may already knew, SQLite allow store TEXT in to a BLOB type column, so both store a UUID string to a BLOB type column and store a UUID hex(16 bytes raw data) to a BLOB type column can be treated allowed. Not like Postgres you mentioned, it always store UUID hex at backend, for SQLite, who knows user want to input each time.

Compare editing inline approach and current approach. 

Currently with SQLiteFlow, if user want to edit a one-line text, user will edit it inline. 
If user want to edit a multi-line text, user will edit it in a popup text editor. 
If user want to edit a blob, user will edit it in a popup hex editor.

Assume editing UUID string inline (and store it as UUID hex) is implemented, user need about 4 steps to finish the editing: 
Copy a UUD string - Click a cell - Paste the UUID string to the cell - Click anther row or double tap Enter key to save the change.

Current approach, user also needs about 4 steps to finish the editing, no extra steps involved: 
Copy a UUD string - Click a cell - Paste the UUID string to the popup hex editor - Click Apply to save the change.

That is to say the editing inline approach doesn't seem win a lot to the current approach.

This is what my current thinking.

**Comment by SQLiteFlow** [comment]
SQLiteFlow(macOS) 5.9.3 has been released.
It contains a few improvements, screenshot attached:
1. A UUID cell will just show a plain UUID string, no prefix or suffix involved.
2. The font of the UUID cell is a fixed width font now.
3. Narrow columns can truncate UUID string smoothly now.
4. In hex editor, the UUID string shows at bottom instead of shows in title.
<img width="1114" alt="1" src="https://user-images.githubusercontent.com/38027540/215232462-4fce38b5-da3c-4782-be2f-5afabc61623d.png">
