### ISSUE TITLE
SDK for connecting database in mobile app with remote connection

### ISSUE THREAD

**Issue by rhult** [SQLiteFlow/SQLiteFlow-Issues#205]
Hi,

Thanks for a great tool! It would be great to have a very simple SDK for setting up a debugging mode in mobile apps that use sqlite. If it was possible to connect the Mac app to the database in the app remotely, that would save so much time and effort when debugging and/or testing the app.

**Comment by SQLiteFlow** [comment]
Honestly I tried to develop a LLDB extension several times to implement similar behavior to let SQLiteFlow(macOS) connect remote debugging app's SQLite database, but all ends up with "Discard changes". It's a little complicated for me.😄

You say a "SDK", do you mean a xxx.framework file that offers services that let SQLiteFlow(macOS) remote connect to?
Actually the LLDB extension option is always my first choice to implement the feature, becuase I assumed people dislike the framework option since it requires embed a unrelate framework file to the App bundle. I don't know if the assumption is correct or not, you're the first one who is taking this topic to me :).

**Comment by rhult** [comment]
Hi, thanks for the quick response! I think by "SDK" I mean the simplest possible way to add the same functionality to any app as your iOS app already has. It could be as simple as just a source file that can be dropped into the sources of any app. I don't know how complicated that part is though. I imagine that the Mac app sends SQL queries to the iOS side, and the iOS side returns the output to the Mac app to be displayed there? I don't think this I would do this with lldb, as it would be great to be able to do this without running the iOS app in the debugger.

An alternative if you don't want to write code for this could be to document the networking protocol so anyone could write the iOS code into their own apps :)

**Comment by SQLiteFlow** [comment]
You're welcome.

> I don't know how complicated that part is though

The complicate part (for me) is co-working with LLDB well, the function itself is already there as you can see in the SQLiteFlow(iOS). 
If SQLiteFlow(macOS) can working with LLDB well one day, when you debug your app with Xcode, SQLiteFlow can use LLDB to access your SQLite database. No extra things required to do with your code bases.

> It could be as simple as just a source file that can be dropped into the sources of any app.

Trust me it will not be just "a" source file, it will be a lot of source files, there're a large number of SQLiteFlow's internal data structures involved. For example, the source files will contain web services module, database query module, and other core data layer modules, etc. So it seems not that simple. 
Also since SQLiteFlow is not a open source project, so a complied framework looks better than the source files.
Drop a complied framework to user's code bases option is technically achievable, I just have worries that I mentioned in the previous post, people may dislike this way.

> An alternative if you don't want to write code for this could be to document the networking protocol so anyone could write the iOS code into their own apps :)

I want to write code for this actually. In my point of view, it is not polite to let users do this.

**Comment by rhult** [comment]
I see! Thanks for your detailed response. I understand that it is a big undertaking. Feel free to close this feature request. And huge thanks for developing the Mac app, it is very useful. Especially the iOS simulator integration is awesome!

**Comment by SQLiteFlow** [comment]
Thank you for understanding. 
This feature is on my list few years already actually, it was in a low priority since these years nobody request it.
Maybe I should keep this issue open and make the priority a litter higher to remind me to investigate more and see what I can do with this.

**Comment by SQLiteFlow** [comment]
> Especially the iOS simulator integration is awesome!

Thank you, I like this feature too.

**Comment by SQLiteFlow** [comment]
Status update.

After some investigation, I get a solution that actually works however it is different to what I originally thought it could be.

The solution is SQLiteFlow can offer two lldb commands: `sfopen` and `sfsave`.

Screenshots attached.

`sfopen <remote file path>` command will automatically copy a remote database to local and then open the local copy with SQLiteFlow.

`sfsave <remote file path>` command will copy the local copy to remote when you want put the database back to remote.

<img width="1176" alt="1" src="https://user-images.githubusercontent.com/38027540/218378498-c67a0ca2-d78f-4c7e-ae31-e6f95d6e5c1a.png">
<img width="1248" alt="2" src="https://user-images.githubusercontent.com/38027540/218378532-6e3b8ac5-aa9c-4ffa-9f3d-6ad60fb929e7.png">

**Comment by rhult** [comment]
That looks pretty good! And if I add a special global variable in debug mode for my app that always points to the database, it will be easy to open it from any breakpoint.

**Comment by SQLiteFlow** [comment]
You're welcome.

> And if I add a special global variable in debug mode for my app that always points to the database, it will be easy to open it from any breakpoint.

Yes, I think it will work.

This feature has been finished already, I will preparing a release to let you have a taste on this feature.

**Comment by SQLiteFlow** [comment]
### SQLiteFlow(macOS) 5.9.5 has been released.
Here's more detail about it. It contains two feature update:
 - LLDB Co-worker, supports `sfopen` command. Let you open a copy of a temporary local database that originally in debugged device.
- LLDB Co-worker, supports `sfsave` command. Let you copy the temporary local database (that originally created by sfopen command) to debugged device.

### How to setup
Add the line below to the file ~/.lldbinit. (If ~/.lldbinit not exists, you need to create one.)
`command script import /Applications/SQLiteFlow.app/Contents/Resources/sqliteflow_lldb_coworker.py`
That's it!
(In Setting - LLDB Co-worker also shows how to setup.)

### What `sfopen <remote file path>` command does
For example: `sfopen "remote/path/to/mysqlite.db"`
1. Copy the remote file to `/private/tmp/com.hyperobjc.SQLiteFlow-macOS.lldbtemp/yourAppBundleID/mysqlite.db`. If `mysqlite.db` exists, it will be replaced.
In additional, `/private/tmp/` is a temporary folder, so the deletion of it's content can be managed by macOS. So that makes if you want to back the database up, you may need to copy the file out of the folder.
3. If `mysqlite.db-journal` or `mysqlite.db-wal` exists in debugged device, it will also be copied to local.
4. Open `mysqlite.db` with SQLiteFlow.

### What `sfsave <remote file path>` command does
For example: `sfsave "remote/path/to/mysqlite.db"`
1. Copy the local file `/private/tmp/com.hyperobjc.SQLiteFlow-macOS.lldbtemp/yourAppBundleID/mysqlite.db` to `"remote/path/to/mysqlite.db"`. If `mysqlite.db` exists in debugged device, it will be replaced.
2. If `mysqlite.db-journal` or `mysqlite.db-wal` exists in local, it will also be copied to debugged device. If `mysqlite.db-journal` or `mysqlite.db-wal` exists in debugged device, it will be replaced.

### The `<remote file path>` parameter
can be a string like `"remote/path/to/mysqlite.db"`,
can be a variable like `dbPath` with type NSString* in Objective-C or String in Swift,
can be a variable like `dbURL` with type NSURL* in Objective-C or URL in Swift.

**Comment by SQLiteFlow** [comment]
Have you tried it yet? If you have, any feedback is welcome :)

**Comment by rhult** [comment]
I get this error when trying:

(lldb) sfopen  /var/mobile/Containers/Data/Application/A9F1519A-AFF3-4733-8C57-10A35DE11976/Documents/test-xxx@xxx.sqlite
Traceback (most recent call last):
  File "/Applications/SQLiteFlow.app/Contents/Resources/sqliteflow_lldb_coworker.py", line 41, in sfopen
    remoteMainDBFilePath = getDBFilePathFromCommand(command)
  File "/Applications/SQLiteFlow.app/Contents/Resources/sqliteflow_lldb_coworker.py", line 256, in getDBFilePathFromCommand
    dbFilePath = evaluateExpression_returnString(command, True)
  File "/Applications/SQLiteFlow.app/Contents/Resources/sqliteflow_lldb_coworker.py", line 219, in evaluateExpression_returnString
    raise Exception("Could not resolve expression: {}".format(expression))
Exception: Could not resolve expression: /var/mobile/Containers/Data/Application/A9F1519A-AFF3-4733-8C57-10A35DE11976/Documents/test-xxx@xxx.sqlite
(lldb) 

I wonder if the special characters in the path can't be handled?

**Comment by SQLiteFlow** [comment]
If sfopen is followed by a string, double quote is required. If the double quote is omitted, then it will be treated as a variable.
For you case, try 
`sfopen "/var/mobile/Containers/Data/Application/A9F1519A-AFF3-4733-8C57-10A35DE11976/Documents/test-xxx@xxx.sqlite"`

**Comment by SQLiteFlow** [comment]
Actually in most cases, if you have a path variable that point to the database,
For example, 
`var myFilePath = NSHomeDirectory() + "/Documents/xxx@xxx.sqlite"`
you can just use 
`sfopen myFilePath`
to do the job, for convenient for purpose.

**Comment by rhult** [comment]
Of course, I was silly! It works nicely, thanks.

**Comment by SQLiteFlow** [comment]
You're welcome. 
And maybe also I should mention this more clearly in the document.
Anyway, if you meet any issues, let me know.
