### ISSUE TITLE
iOS/macOS Shortcuts compatibility

### ISSUE THREAD

**Issue by benyn** [SQLiteFlow/SQLiteFlow-Issues#215]
SQLiteFlow's support for Shortcuts is fantastic but unfortunately iOS and macOS apps don't share Shortcuts Actions. On macOS, I see "Unknown Action" for the SQLiteFlow iOS app's Shortcuts actions and vice versa. I understand that they are two different apps, but would it be possible for them to share the same Shortcuts actions?

I could be wrong but I believe it's possible given [Things for Mac](https://apps.apple.com/us/app/things-3/id904280696?mt=12) and [Things](https://apps.apple.com/us/app/things-3/id904237743) are two separate apps that are purchased separately, but they share the same Shortcuts actions.

**Comment by SQLiteFlow** [comment]
Thank you for using SQLiteFlow.

They can't share same Shortcuts action is mainly because they are in different sandbox environment.

In detail, if you have a SQLite database located in `myFolder/myDB.db`, on macOS, SQLiteFlow only need to get the access permission of the file `myDB.db` to work with the database correctly. However on iOS, SQLiteFlow need to get the access permission of the folder `myFolder` to work with the database correctly.

And this is why on iOS, you have to open and external folder first to open and external SQLite database.
This is same when you config Shortcut actions, on iOS, you can only select databases that in the external folder that you already added in the main app (to make sure the action have correct file access permission) to run against, on macOS, there's no such logic, that is to say, when you config Shortcut action, you select database file directly to run against.

Additional references:
Write a universal Shortcut action (more like a workaround though): https://github.com/SQLiteFlow/SQLiteFlow-Issues/issues/171#issuecomment-976340872
And there're also other differences about Shortcut actions between iOS and macOS which mentioned here:
https://github.com/SQLiteFlow/SQLiteFlow-Issues/issues/171#issuecomment-976359350
