### ISSUE TITLE
App does not work when not connected to the internet

### ISSUE THREAD

**Issue by ReagentX** [SQLiteFlow/SQLiteFlow-Issues#232]
**Version**
 - Platform: macOS Sonoma 14.4.1 (23E224)
 - SQLiteFlow: 6.3.6
- Purchased through App Store

**Steps to Reproduce**

- Open the app offline

**Expected behavior**

- The app runs

**Screen shots**

<img width="732" alt="Screenshot 2024-04-26 at 1 39 12 PM" src="https://github.com/SQLiteFlow/SQLiteFlow-Issues/assets/1920666/34a85818-ceec-48e2-88de-9d17c9e278f3">

**Comment by SQLiteFlow** [comment]
I believe this only happens when at the app very first run, am I right?

When at the app very first run, it need to download the app transaction info from the App Store server if the info is not stored at local. 
(Usually the app transaction info is downloaded when you download the app, but sometime not downloading may happen.)

**Comment by ReagentX** [comment]
No, it's not the first run. I use the app all the time, it's very useful for my workflow in [`imessage-exporter`](https://github.com/ReagentX/imessage-exporter)!

**Comment by SQLiteFlow** [comment]
> I use the app all the time, it's very useful for my workflow in [imessage-exporter](https://github.com/ReagentX/imessage-exporter)!

I'm glad to hear it's useful for you!


> No, it's not the first run.

That's weird, since it's totally fine to open the app offline at my side. Screenshot attached.
So in your case, the app is able to open normally when there's a network, but can't open normally when go offline, right?

<img width="1176" alt="1" src="https://github.com/SQLiteFlow/SQLiteFlow-Issues/assets/38027540/5d21eaa3-deb3-41a5-8bed-51e73afb6b44">

**Comment by ReagentX** [comment]
My situation is that I am sometimes connected to a local network but not the public internet. In those situations I get the `-1008` error. 

If I do the same thing as you, i.e. fully disconnect from everything and disable those interfaces, you are correct that the app launches successfully.

**Comment by SQLiteFlow** [comment]
> the app launches successfully.

When it launches successfully, then if you check the license state through Main Menu - SQLiteFlow - Purchase Plan, it is `Lifetime License` right?

If the app could show `Lifetime License` correctly, this means the app transaction info has been downloaded to local correctly. 

And if it downloaded correctly, the app should launch successfully regardless of what network condition you are in.

I tried to disconnect the public internet through my router, I can open the app successfully, and when I go to Main Menu - SQLiteFlow - Purchase Plan, after waiting for a long time,  I can see the -1008 error too, screenshot attached. The error is throwing by StoreKit when the app is calling it to get all purchase plans info. But this error only appears on this page and should not affect you to use the app.

So at my side, the app can launch successfully regardless of what network condition I'm in.

But at your side, when you launch the app with the local network only condition, it display the purchase plan page directly, and not display the main app?

<img width="596" alt="2" src="https://github.com/SQLiteFlow/SQLiteFlow-Issues/assets/38027540/c3c11772-9f39-4948-b61f-117cf09315bf">

**Comment by ReagentX** [comment]
I always get the `-1008` error when I launch the app without access to the internet. It opens to the license screen, not the main app window, and eventually emits the error.

**Comment by SQLiteFlow** [comment]
When you go online, does it launch correctly? 
And what purchase plan page displays when it launch correctly?

**Comment by ReagentX** [comment]
Yeah, when the network is normal I can use the app fine. The purchase page looks normal: 

<img width="732" alt="image" src="https://github.com/SQLiteFlow/SQLiteFlow-Issues/assets/1920666/99de9f0e-987c-41e5-818d-c44e2b4a0ca6">

**Comment by SQLiteFlow** [comment]
I use this way to setup a _local network_ environment:

Let a Mac (Mac Studio 2022 with macOS Sonoma 14.4.1) connect to a router through a cable, then let the router disconnect from public internet.

But apparently this configuration let me failed to reproduce this issue, the app just launches fine without any issue.

I also use a iPhone which is connected to this router to launch the SQLiteFlow(iOS) app, since the iOS app share the same relative logic with Mac, but the iOS app could launches fine without any issue too.

So maybe the _local network_ is not the underneath issue that triggering this bug? I'm not sure.

Does re-downloading the app from App Store, or restoring previous purchase could fix the issue?
Or do you have more environment setup info that can let me take something more to try to reproduce the issue?

<img width="651" alt="1" src="https://github.com/SQLiteFlow/SQLiteFlow-Issues/assets/38027540/1e8f483f-16e1-44e6-8d15-dd12b6656c9e">

**Comment by ReagentX** [comment]
I don't know what changed but I can no longer replicate the problem.

**Comment by SQLiteFlow** [comment]
That's nice to hear.

My theory is when you open the purchase plan page normally, the app transaction info has been refreshed correctly.
