### ISSUE TITLE
Sharing Between Accounts on Same Mac

### ISSUE THREAD

**Issue by gitgirl777** [SQLiteFlow/SQLiteFlow-Issues#236]
**Version**
 - Platform: [e.g. macOS 13.0]
 - SQLiteFlow: [e.g. 5.8.0]
Hi There - I have family sharing enabled, and switch between users on my macbook. They're both for me with separate apple id's. But I have to log out of my other apple id and log back into the originally purchased one despite having shared it on our family plan. I'm just logging in as an additional user on the same computer. Thank you.

**Comment by SQLiteFlow** [comment]
What's your expected behavior and what's actually happens?

**Comment by danielpox** [comment]
I have this issue as well.

I purchased the lifetime license (full app) on my **previous** Apple ID. (The price back in 2019 was different from the current price for the same in-app purchase.)

In order for me to use the app on iOS, I have to go to the App Store, log out from my current Apple ID account, log in to my old one, and then open the app again.

Whenever I switch back to my personal Apple ID in the App Store again, and try to use the app, I'm prompted with the in-app purchase dialog.

Despite having enabled Family Sharing on the two accounts, it doesn't work.

It also doesn't work to restore purchase, because then it prompts me for my **current** Apple ID password. Then nothing happens.

I would like access to the app without having to switch accounts on the App Store every time.

**Comment by SQLiteFlow** [comment]
> Whenever I switch back to my personal Apple ID in the App Store again, and try to use the app, I'm prompted with the in-app purchase dialog.

After some investigation, this happens when SQLiteFlow switched to use [StoreKit 2](https://developer.apple.com/storekit/) to invalidate in-app purchases, which the OS now handle over the invalidating process, that is to say, the process of determining if user purchased the license is out of the app's control now. 

In your case, when you switch to use your personal Apple ID, and when you launch the app, the OS may tell the app that there no validate purchase exists, this is why the app will prompt the in-app purchase dialog.

From this analysis, I believe you may see more apps behave like this when more apps switch to use StoreKit 2.

> Despite having enabled Family Sharing on the two accounts, it doesn't work.

It never worked, because Family Sharing is not enabled for the life-time license.

**Comment by danielpox** [comment]
Thank you for your fast response.

So, there's nothing you or I can do about this? (Other than switching accounts in the App Store.)

And I assume there's no way to transfer the purchase to a different account either, from Apple's side.

Either way, I want to express my appreciation of this app! It's an incredible tool for iOS 😁

**Comment by SQLiteFlow** [comment]
> So, there's nothing you or I can do about this?

Technically yes.

**Comment by SQLiteFlow** [comment]
@danielpox Are you sent a message already? I have not received any yet. I want to send you a message via email😄.

**Comment by danielpox** [comment]
I did just now. From a poxmedia address.

**Comment by SQLiteFlow** [comment]
@danielpox Message sent.
