### ISSUE TITLE
NSURLErrorDomain

### ISSUE THREAD

**Issue by jdarchiwarede** [SQLiteFlow/SQLiteFlow-Issues#246]
**Version**
 - Platform: [e.g. macOS 13.6.7]
 - SQLiteFlow: [e.g. 6.4.2]
- AppStore order: MN3ZV65XBX
![Bildschirmfoto 2024-10-04 um 11 08 03](https://github.com/user-attachments/assets/6005a5e0-7314-43ac-acf6-d6b93cde7694)

I get the error message “The operation could not be completed. (NSURLErrorDomain error -1008).”
I have already tried to restore the previous purchase, but it always ends with this error.

thx
--
Josef

**Comment by SQLiteFlow** [comment]
When you say you get the error message  “The operation could not be completed. (NSURLErrorDomain error -1008).”, you mean you get it on the Purchase Plan page, right?

Can you launch to the main app normally now?

The latest version of SQLiteFlow(macOS) now is 6.5.0, does delete the app then re-download the latest version could solve the problem?

**Comment by jdarchiwarede** [comment]
I installed 6.5. After that, I should log in with my Apple ID. But that doesn't work. After I enter my password, after about 2-3 seconds I get the prompt to log in again. And that repeats itself. I have already tested whether there is a problem with my password. But that seems to be okay.

**Comment by SQLiteFlow** [comment]
That's seems like glitch of the App Store or a network problem, since the password prompt dialog is belong to the system (macOS).
Could you test that if you are able to download any free app that you never got once from the App Store at your side?
And could you test if the restoring purchase feature that offered by another app on your system also doesn't work?

**Comment by jdarchiwarede** [comment]
I updated all my current apps from within the App Store application. And the same dialog pops up, asking me to sign in with my Apple-ID. And that works fine.

**Comment by SQLiteFlow** [comment]
Then does others app's restoring previous purchase feature works fine too?

**Comment by jdarchiwarede** [comment]
I can't say, because all the other applications work. I just bought Cyberduck in the store and everything worked without a problem.

**Comment by SQLiteFlow** [comment]
Cyberduck does not offer in-app purchase, so it does not using any in-app purchase SDK, and it does not need to offer restore previous purchase feature.

But what you're seeing is restoring in-app purchase error.

Have you tried using a cellular network instead of office WiFi (for example, by connecting a personal hotspot through iPhone) to do the restoring purchase?

**Comment by jdarchiwarede** [comment]
Yes, I change the network already. Same problem. I don't think I have another in-app purchase.

**Comment by SQLiteFlow** [comment]
Aah, that's a tough issue (for me) to discover what cause that.
I attached the video here to show everything work fine at my side.

I don't know if this work, but does restart your Mac work? Or do you have any other Macs to see if this problem persist on these Macs?

https://github.com/user-attachments/assets/e1dcbc48-1d2a-4680-936e-68a40ef78094

**Comment by jdarchiwarede** [comment]
I was afraid you were going to suggest a restart. I hate restarts, but I'll do it.

**Comment by jdarchiwarede** [comment]
After restarting, it worked straight away. There was also no dialog to sign in with the Apple ID. I do not understand it.
Thank you for your time!

**Comment by SQLiteFlow** [comment]
You're welcome. And it's good to hear, that's also a release to me.

> I do not understand it.

That's no doubt a macOS's bug.

If you experience other issues, please don't hesitate to let me know.
