### ISSUE TITLE
Allow to edit Plist saved as blob type.

### ISSUE THREAD

**Issue by moinzeta** [SQLiteFlow/SQLiteFlow-Issues#249]
**Version**
 - Platform: macOS 14.7
 - SQLiteFlow:6.5.0

I have one table which stores plist as blob type. I can able to preview it but I want to do some experiment via changing some of the value. so if we have feature like update or replace the values then it would be very helpful.

**Comment by SQLiteFlow** [comment]
> I can able to preview it but I want to do some experiment via changing some of the value.

How do you do it now?

**Comment by moinzeta** [comment]
as of now I am doing by adding code while inserting records. 
for eg. if I want to mock something or want to do changes on run time I intercept insert via programming and do required changes in data and then insert to db.
for ex one key has value true and I want it to false then i change data after receiving from api call and then insert to db.

**Comment by SQLiteFlow** [comment]
I see. Then why not use "Save As..." to save the plist as a file, then after you edit the file by Xcode, use drag and drop or "Open File to Replace.." to reload the file to the Hex Editor?
<img width="1210" alt="pic" src="https://github.com/user-attachments/assets/7a3c94ea-2019-47df-a1e1-eb4984411f4d">

**Comment by moinzeta** [comment]
got it, it will work. if you could give inline plist editor then it would be very good feature for the app. 

if you add multiline text editor which will help to edit long text (just a suggestion)

**Comment by SQLiteFlow** [comment]
> got it, it will work. if you could give inline plist editor then it would be very good feature for the app.

Thank you for the suggestion. I may in future find a way to let SQLiteFlow's Hex Editor co-work with an external editor (Xcode in this example) to update data. So that you can not only edit plist data, but also other types of data that you can edit with an external editor.

> if you add multiline text editor which will help to edit long text (just a suggestion)

You can, just right click a text cell - Edit as Text to edit long text. Screenshots attached.
<img width="1041" alt="a1" src="https://github.com/user-attachments/assets/a8176858-aca3-4ea0-86c3-654d0e0cd0f8">
<img width="1086" alt="a2" src="https://github.com/user-attachments/assets/ced38b4b-26ab-4add-b0e8-1df8b916bf7f">

**Comment by moinzeta** [comment]
thanks brother. this information will help a lot.

**Comment by SQLiteFlow** [comment]
You're welcome, brother.

**Comment by SQLiteFlow** [comment]
We apologize for the long wait.
The “Open with External Editor” feature for Hex Editor has been implemented and is now available on the Mac App Store.

Screenshot attached.

<img width="1143" height="762" alt="Image" src="https://github.com/user-attachments/assets/3cd961bc-143d-4fea-9ef8-d498da9d5073" />
