### ISSUE TITLE
Format JSON columns

### ISSUE THREAD

**Issue by xiruizhao** [SQLiteFlow/SQLiteFlow-Issues#253]
**Version**
 - Platform: iOS 18.1
 - SQLiteFlow: 6.5.2
 
Can you add a button to format json text data? Already formatted json data will open a separate text editor, but unformatted single line json data won't. Plus I want to make sure any changes are properly formatted too.
Thanks!

**Comment by SQLiteFlow** [comment]
Short answer, I would like to.

> Already formatted json data will open a separate text editor, but unformatted single line json data won't.

This is caused by multiline text is forced editing on a separate text editor. Single line text can edit in place, if you want to edit a single line text on a separate text editor, you can long press the text cell to bring up a context menu, then tap Open in Text Editor.

Currently SQLiteFlow lack of ability of detecting if a piece of text is in JSON format, mainly because of performance concerns. I may need to add some logic to quick detecting it in future version of SQLiteFlow, but may result in false negative, which means real JSON text may be treated as arbitrary text because of this.

Or I may not need to detecting if a piece of text is JSON at all, all what I need to do is add a formatting JSON button to the Text Editor. I'm not sure yet, what do think about it?


> Plus I want to make sure any changes are properly formatted too.

Add a button of formatting JSON is easy, I believe you can always tap this button before you save.

**Comment by xiruizhao** [comment]
Thank you so much for the quick response! Yeah I think just adding a button to format JSON is enough.

**Comment by SQLiteFlow** [comment]
Version 6.5.3 has been released, you can download it and take a try now.

**Comment by SQLiteFlow** [comment]
Does it looks good?

**Comment by xiruizhao** [comment]
Yes exactly I wanted
Thank you!
