### ISSUE TITLE
[iOS] Supports context menu preview in Data Editor and Query Results for iOS 13

### ISSUE THREAD

**Issue by wilpert** [SQLiteFlow/SQLiteFlow-Issues#60]
There is no possibility currently to change the displayed font size. This is something that in my opinion should be implemented as a quite standard feature, especially in small screen sizes as in the iPhone.

But even after changing the font size some of the columns will not be able to display the content fully. It would be therefore very useful, if the size of the displayed columns could also be changed.

**Comment by SQLiteFlow** [comment]
@wilpert Thank you for the feedback.

What if we can let the Data Editor's text size respect to iOS Setting's text size (Settings - Display & Brightness - Text Size), and the column width can be automatically adjusted when the text size changed in iOS Settings, does this sound good for you?

**Comment by wilpert** [comment]
@SQLiteFlow Thanks a lot for the quick response.

I am not so concerned about the size of the font itself but the main issue I have is that texts in a column beyond a certain length threshold (and possibly depending also on the number of columns displayed) are not shown complete, they are cut and end in three dots (see screenshot below). I suspect that changing the font size and letting the columns be adjusted automatically will not solve this problem, the column widths will just get narrower.

![screenshot](https://user-images.githubusercontent.com/7935490/65747451-bcc8bd80-e101-11e9-9bea-6cc19acb8e8c.png)

I see at least the following solutions:
- The column widths are adjustable, as proposed initially.
- The complete text is displayed if the corresponding entry in the column is touched (hover text).
- The width of the column is automatically adjusted to fit the longest text in that column. This could lead, depending on the number of columns and the length of the text within them to huge horizontal size of the whole view requiring heavy left and right scrolling. Probably best as a user setting.

**Comment by SQLiteFlow** [comment]
@wilpert You are welcome, and thank you for the reply.
I think I get your point. Then how about these solutions, similar to what you mentioned but with some changes:
- A column's width can be changed by user to any value. A possible implementation is by long press a column's title, then user can input a value of the width to set.
- And as you mentioned, auto set column width to a very big value is probably not a good idea, currently there's a max column width which is 640 point when a column' width be automatically set in the spreadsheet, I think keeping it in that way can avoid to bring some not good user experiences. 
- Then how to complete display a long text without user manually change column width? One of an idea is adding an option 'Edit as Text' in text field's context menu, so user can choose it to navigate to a new page or a larger area to view/edit the text.
- Currently for performance reason, we don't calculate all rows in a column to get the longest text's width for setting a column's width. But that can be improved, since the main goal here is to automatically determine a reasonable initial width for that column.

What do you think about these?

**Comment by wilpert** [comment]
@SQLiteFlow thanks again!

I think that the idea of changing the column's width by entering a vlaue is not good, since the user will not know most of the times which value exactly is needed to display the whole text in the column and this will lead to a trial and error process. It would be better if the column width could be adjusted via a handle that would be activated when touching the delimiting line between two columns; swiping left or right would decrease or increase the column width. Nevertheless I think the "hovering text bubble" solution that I Mention below ist more elegant.

The idea of editing the text via text field's context menu ist much better. However I think it is too cumbersome if it leads to a new page. An in-place editing area would be preferred. But since in a view or in the query results page we do not want to edit the text, I think the best solution would be to display the full text in a hovering text "bubble" (sorry, I do not know the technical GUI Name for it) when long pressing the entry, like "Delete Row" in the following screenshot:

![screenshot](https://user-images.githubusercontent.com/7935490/65755532-957aec00-e113-11e9-95b3-af5021f65f4c.png)

This should be possible both in a "view" and in the results page after running a query. What do you think?

**Comment by SQLiteFlow** [comment]
@wilpert 
I think what you said make sense, I now prefer the 'bubble' way too.

The 'Delete Row' bubble is called menu controller or context menu, with that way, I think I will add an extra column to the left edge of the spreadsheet to let user select a row, and an opportunity to delete a row.

The long press gesture in the a data cell will trigger to show a 'bubble' instead of the 'Delete Row' context menu.

The 'bubble' is actually a preview of the text, the preview bubble will behaves exactly like the preview bubble when you long press a website link in Safari at iOS 13 (I attached an animated GIF to demonstrate that), with that way, when the preview bubble displaying, you can see the preview of the text, then if you want the preview bubble go away, you can just tap an empty area to dismiss it, and if you want open the preview in a new page, you can just tap the preview bubble to do that.

Now, sounds good to you?

![AnimatedGIF](https://user-images.githubusercontent.com/38027540/65763720-9719d380-e156-11e9-8a47-1ac7234056d3.gif)

**Comment by wilpert** [comment]
@SQLiteFlow: that sounds like an awesome solution!

Thanks a lot for taking the time to discuss it.

**Comment by SQLiteFlow** [comment]
@wilpert 
Thank you too.
I will work on it in a few days and will let you know when this feature is available.

**Comment by SQLiteFlow** [comment]
Finished coding.
1. Long press a text cell, the preview of the text will pop up along with a context menu which contains 4 items: 'Copy', 'Open in Text Editor', 'Set NULL' and 'Share'.
2. Long press a blob cell, the preview of the blob will pop up along with a context menu which contains 4 items: 'Copy as Hex String', 'Open in Hex Editor', 'Set NULL' and 'Share'.
3. Long press left edge of a row,  a context menu which contains 2 items: 'Copy Row' and 'Delete Row' will show up.

![previewtext](https://user-images.githubusercontent.com/38027540/71137470-4a203780-2243-11ea-9b0e-98dc54272694.gif)
![previewimagegif](https://user-images.githubusercontent.com/38027540/71137501-560bf980-2243-11ea-92ef-52864229a780.gif)
![row](https://user-images.githubusercontent.com/38027540/71137511-60c68e80-2243-11ea-9958-777789397a27.png)

**Comment by SQLiteFlow** [comment]
@wilpert SQLiteFlow(iOS) 4.0.0 has been released.
Happy new year!

**Comment by wilpert** [comment]
@SQLiteFlow Thanks a lot for the implementation and Happy New Year to you too!

**Comment by SQLiteFlow** [comment]
@wilpert You're welcome! And thanks!
