### ISSUE TITLE
[iOS] Import CSV from file causing unreadable code imported to table when the CSV file can't read with UTF-8 encoding normally.

### ISSUE THREAD

**Issue by sugrass** [SQLiteFlow/SQLiteFlow-Issues#71]
請問這軟體支援繁體中文嗎？
我試用的結果是亂碼
![DE6BAFCA-4558-4FED-B21E-DDF115F0E1F5](https://user-images.githubusercontent.com/58017086/69299997-ff63cd80-0c4c-11ea-82f4-c8f2a96cbe82.jpeg)

**Comment by SQLiteFlow** [comment]
@sugrass，謝謝您的反饋。
是的，SQLiteFlow支援繁體中文。
對於您提出查詢結果亂碼的問題，可以提供給我們更多的資訊嗎？
1. 截圖中有問題的欄位，它的列型別是什麼呢？
2. 這個欄位的內容是什麼，是一個字串還是一些原始二進位制資料呢？

@sugrass, thank you for your feedback.
Yes, SQLiteFlow supports Traditional Chinese.
For the issue that you mentioned, can I get more information?
1. What the type of this column is?
2. What the content of the field is, is it a string or raw binary values?

**Comment by sugrass** [comment]
你好，
我是用CSV檔匯入，欄位格式是文字。
我全部的欄位都是文字，但不知怎麼會亂碼

**Comment by SQLiteFlow** [comment]
@sugrass，可以提供給我們有問題的CSV內容嗎，我們試著重現一下這個問題。

@sugrass, can I have the CSV content that causing the issue, So I can try to reproduce the issue.

**Comment by sugrass** [comment]
請問，
是直接這裡給你檔案嗎？
謝謝

從我的iPhone傳送

**Comment by SQLiteFlow** [comment]
@sugrass，只提供給我們導致亂碼的CSV文字就可以了，因為也有可能是匯入CSV文字的時候出了問題，但這需要調查後才知道。

@sugrass, you can send us the CSV text that causing the issue, so we can research if there's something wrong with the CSV importing feature.

**Comment by sugrass** [comment]
so can i send the file by email this way?
thanks

從我的iPhone傳送

**Comment by SQLiteFlow** [comment]
@sugrass， 如果CSV文字不长，又没有什么隐私内容的话，您可以把它直接粘贴在这里就好了。
如果您想传送文件，您可能需要到GitHub网页端来将文件拖拽到回复框来添加文件。
因为直接通过email附加文件来回复我们应该看不到这个文件。

@sugrass, if the CSV text is not long and has no private content, it's okay to just paste it here.
If you prefer transfer a file directly, you may need to visit the GitHub web page to attach it. Since we may not see it if you attach the file by directly reply the email.

**Comment by SQLiteFlow** [comment]
@sugrass， 如果CSV文字不長，又沒有什麼隱私內容的話，您可以把它直接貼上在這裡就好了。
如果您想傳送檔案，您可能需要到GitHub網頁端來將檔案拖拽到回覆框來新增檔案。
因為直接通過email附加檔案來回復我們應該看不到這個檔案。

@sugrass, if the CSV text is not long and has no private content, it's okay to just paste it here.
If you prefer transfer a file directly, you may need to visit the GitHub web page to attach it. Since we may not see it if you attach the file by directly reply the email.

**Comment by sugrass** [comment]
你好，
我上傳了我的csv檔給你試試，感謝！
[test1.zip](https://github.com/SQLiteFlow/SQLiteFlow-Issues/files/3872755/test1.zip)

**Comment by SQLiteFlow** [comment]
@sugrass, 檔案已經收到，正在調查。謝謝。

@sugrass, the file received, I'm looking into it. Thank you!

**Comment by sugrass** [comment]
謝謝你，若真可以解決，那我就要在iphone上訂購了

**Comment by SQLiteFlow** [comment]
@sugrass 謝謝。

這個bug是由於在匯入CSV檔案時，沒有正確處理檔案編碼所致。
已經在最新程式碼中修復。下面附加了一張圖片和一個演示視訊。

在新版本釋出之前，變通的辦法有兩種，分別為：
1. 將CSV檔案轉為UTF-8編碼後，再進行匯入。
2.更換匯入CSV的方式，選擇匯入方式為從CSV文字匯入。

@sugrass Thanks.

This bug is caused by not handling text encoding correctly when importing a CSV file.
It has been fixed in the master branch. A picture and a demo video have been attached.

And before the fixed version released, there're two workarounds:
1. Convert the CSV file to a UTF-8 encoded file before import it.
2. Change the 'Import From' field to 'CSV Text'.

![Demo](https://user-images.githubusercontent.com/38027540/69336661-ffd68580-0c99-11ea-87a0-6a8284d081ff.png)
[Demo.mov.zip](https://github.com/SQLiteFlow/SQLiteFlow-Issues/files/3874535/Demo.mov.zip)

**Comment by sugrass** [comment]
hi，

感謝你的協助並提供了可能的方法，
不過還有一個小疑問
utf-8的問題我昨天有想過，不過找不到從哪裡轉檔？
請問能協助一下教我怎麼轉utf-8的檔案嗎？
感謝！

準備從appstore來買此軟體，感謝你的協助。
謝謝
Net

從我的iPhone傳送

**Comment by SQLiteFlow** [comment]
@sugrass
當然。我在macOS下是這麼做的，如果您在Windows，我想步驟應該差不多。我不太確定是不是有更高效的做法，不過這幾步對我來說是可以工作的。
1. 將檔名從 「test1.csv」改為 「test1.txt」。
2. 在Chrome瀏覽器中開啟檔案「test1.txt」。
3. 「test1.txt」中的內容會出現在Chrome中。
4. 把內容複製貼上到一個文字編輯器比如Sublime Text中, 然後 File - Save with Encoding - UTF-8
5. 儲存後，您就得到了一個已UTF-8編碼的檔案。

@sugrass 
Sure. Here's my steps in macOS, if you are in Windows, I thinks the steps are similar. Not quite sure about if there're more efficient ways to do that, but these steps work for me.
1. Change the file name 'test1.csv' to 'test1.txt'.
2. Open the file test1.txt in Chrome (the web browser).
3. Then the file test1.txt's content will shows up in Chrome. 
4. Copy & paste the content to a text editor like Sublime Text, then File - Save with Encoding - UTF-8.
5. Then you get a file that encoded with UTF-8.

**Comment by sugrass** [comment]
Hi ,

It's a good idea .

Thanks for your supports.

Thanks again
Net

從我的iPhone傳送

**Comment by sugrass** [comment]
不好意思，
再請問一下，這軟體安裝在iphone手機裡，我有辦法用windows系統與這手機資料庫連線嗎？
謝謝

從我的iPhone傳送

**Comment by SQLiteFlow** [comment]
@sugrass 
您可以使用iTunes的File Sharing功能，來將資料庫從iPhone複製到Windows，或者將資料庫從Windows匯入到iPhone。iTunes的File Sharing的截圖已經附加的下面。
但是目前還不支援在Windows中直接連線（開啟）在iPhone中的資料庫。

@sugrass 
You can use iTunes's File Sharing feature, to copy SQLite databases from iPhone to Windows, or import SQLite databases from Windows to iPhone. An image for iTunes's File Sharing has been attached.
But we currently not support connect (or open) SQLite database in iPhone from Windows yet.

![61842035-5210c100-aec9-11e9-85aa-92a1874b36c6](https://user-images.githubusercontent.com/38027540/69635451-5e7f7300-108f-11ea-9ab3-31176de3a442.png)

**Comment by SQLiteFlow** [comment]
@sugrass
或許您是在好奇SQLiteFlow(iOS)的「連線」功能有什麼用。

是這樣的，SQLiteFlow現在有iOS端和Mac端兩個版本，SQLiteFlow(iOS)的「連線」功能可以讓SQLiteFlow(macOS)像開啟本地資料庫那樣開啟在SQLiteFlow(iOS)中的資料庫，以方便開發者在電腦端除錯在手機端的SQLite資料庫。

由於SQLiteFlow目前還沒有Windows版，所以對於Windows使用者來說，這個功能暫時還沒有什麼用處。

@sugrass
I was wonder maybe what you are curious about is the 'Connect' feature in SQLiteFlow(iOS).

Well, SQLiteFlow now can run in both iOS and Mac, the 'Connect' feature in SQLiteFlow(iOS) can let SQLiteFlow(macOS) open databases in SQLiteFlow(iOS) like open local databases, so developer can debug SQLite database in iPhone on a desktop computer.

Because of there's no Windows version of SQLiteFlow yet, so currently this feature is kind of not so useful for Windows users.

**Comment by SQLiteFlow** [comment]
SQLiteFlow(iOS) 4.0.0 已經發布。
新年快樂！
