### ISSUE TITLE
Cancel free subscription. 【Answered, no need to cancel, since the free trial is a one-time in-app purchase, not a subscription.】

### ISSUE THREAD

**Issue by Alfie8274** [SQLiteFlow/SQLiteFlow-Issues#90]
Hello,

I activated the free subscription just to try out the app. However because I don’t have a use for it I want to cancel it. How do I cancel the free subscription? 

Many thanks

**Comment by SQLiteFlow** [comment]
@Alfie8274 
Thank you for tried out the app. 
And for the question, you don’t need to cancel anything, because the free trial is just a one-time in-app purchase which cost $0, it’s not a subscription type in-app purchase. That is to say, after the free trial ends, you won’t need to pay anything.
So if you don’t have a use for the app, it’s safe to just delete it.
And if you miss the app someday in future, you can re-download it from the App Store and purchase the Full App one-time in-app purchase to unlock the app :)
