### ISSUE TITLE
SQL Formatting

### ISSUE THREAD

**Issue by bitxianaiz** [SQLiteFlow/SQLiteFlow-Issues#96]
This is the way this app formats SQL
![SQLiteFlow Format](https://user-images.githubusercontent.com/64098128/80164469-077ebb00-85a7-11ea-83f8-6422c4169083.png)

Q: Can users permanently change the way this app formats SQL?

Q: What is the Copy Query in Preferences, how is it used and what is its purpose?

THANK YOU

**Comment by SQLiteFlow** [comment]
@bitxianaiz 

Q: Can users permanently change the way this app formats SQL?
Could you offer me an example? Since I'm not quite understand the question.

Q: What is the Copy Query in Preferences, how is it used and what is its purpose?
It affects to 'Copy with Custom Style' in Query Editor's right click menu, see screenshot attached.
Purpose:  for instance, if a developer is developing an app using Swift and SQLite for example, if the developer wants to query the database, he/she needs to construct a query string first of course, the query string I mentioned is something like 
```
var sql = ""
sql.append("SELECT ")
sql.append("   * ")
sql.append("FROM Student; ")
```
The feature  'Copy with Custom Style' can let developer directly copy a constructed query string and paste it to their code conveniently.

![ScreenShot](https://user-images.githubusercontent.com/38027540/80167047-03d44e00-8612-11ea-9c55-c177f97c1cb3.png)

**Comment by bitxianaiz** [comment]
>> Could you offer me an example? Since I'm not quite understand the question.

Sure-- Take a look below at how sqliteflow formats queries either when making changes using the Alter Table UI or in the Query Editor when I press Command-I (Editor > Structure > Format Query)
![SQLiteFlow Format](https://user-images.githubusercontent.com/64098128/80218401-22851580-860f-11ea-87fd-aecd38dc7b15.png)

The question was if the sqliteflow user was able to change the way sqliteflow formats SQL to, say,  something like this:
![Custom Format](https://user-images.githubusercontent.com/64098128/80218659-768ffa00-860f-11ea-8851-aea48c0681a4.png)

And also if the sqliteuser is able to change some basic query editor features like the number of TAB spaces  and whether to use TABS or spaces. The Query Editor seems to use size-4 indented TABS but the sqliteflow formatted queries use size-3 indented Spaces instead of TABS.

**Comment by SQLiteFlow** [comment]
@bitxianaiz 
1. Add the capability to set number of Tab Spaces for Query Editor is possible, and it can be available in next version.
2. It's also possible to add some settings to let user customize the behavior of Format Query. For example, let user choose if he/she would like to put the comma that split column definition at next line, would you like me to add this setting in future version?
3. For 'whether to use TABS or spaces' you mentioned, if you mean let user choose whether to use Tabs or Spaces as indentation for Format Query, well, probably can, but need further investigation for this one.

**Comment by bitxianaiz** [comment]
>> 1. Add the capability to set number of Tab Spaces for Query Editor is possible, and it can be available in next version.

The standard I've used and seen for many years in SQL code is to use TABs instead of Spaces, and the TAB size is 4 (equivalent to 4 spaces).

>> 2. It's also possible to add some settings to let user customize the behavior of Format Query. For example, let user choose if he/she would like to put the comma that split column definition at next line, would you like me to add this setting in future version?

Yes. Ideally, the app-generated formatted query would use size-4 TAB indentation and allow for traditional trailing commas. IMO, I find the esoteric left-side next line commas to be quite confusing and disturbing.

>> 3. For 'whether to use TABS or spaces' you mentioned, if you mean let user choose whether to use Tabs or Spaces as indentation for Format Query, well, probably can, but need further investigation for this one.

Until then, what is important is that both the Query Editor and the app-generated code consistently use size-4 TABs for indented code. Right now, the Query Editor uses size-4 TABs indents but the app-generated code uses 3-space indents.

Query format is very important in SQLite because, as opposed to all other RDMS databases, SQLite stores the database schema as text queries instead of system tables and so the format of the original query used on table and view creation (good, bad or ugly) will live forever in the database schema.

Two more points while you're at it. (a) Make sure to trim out any trailing right spaces on your app generated queries. (b) This on is more involved and perhaps it should be a separate issue: Basically it has to do with the information on this SQLite web page: https://www.sqlite.org/lang_altertable.html. Specifically, it has to do with the correct and incorrect procedure to alter a table and preserve the existing table data--screenshot below. FYI, I believe SQLiteFlow may be using the incorrect sequence.

![Screen Shot 2020-04-27 at 9 03 56 AM](https://user-images.githubusercontent.com/64098128/80375611-979e5800-8866-11ea-8d5f-0b038b51a863.png)

**Comment by SQLiteFlow** [comment]
@bitxianaiz 
Okay I see. I think at least two settings need to be added for now.
One is allow user to set Tab Width (space as unit) for Query Editor.
Another is allow user to set Indent Width (space as unit) for Format Query.
User can set both the two fields's value to 4 spaces of course.

And further more, I will see if it's possible to add one more setting to let user choose the prefer indent using Spaces or Tabs for Format Query.

And for the two more points:
(a) 
1. Format Query never generate trailing right spaces.
2. Copy Query with Custom Style will generate trailing right spaces as default, you can change that in Preference - Copy Query - Line End field to `\n")` or whatever you like. 
In addition, leave it like `")` is not recommended because it may cause SQL spell incorrectly. For example, it may cause two words combined to one word because there're no space(s) between the two words.

(b) You are right, SQLiteFlow better follow the Correct steps from the SQLite documentation, I will create another [issue](https://github.com/SQLiteFlow/SQLiteFlow-Issues/issues/99) to track this.

**Comment by SQLiteFlow** [comment]
1. Added a setting 'Tab Width' to 'Preference - Text Editing' to allow users set Tab width.
2. Added a setting 'Prefer Indent Using' to 'Preference - Format Query' to allow users set prefer indent using 'Spaces' or 'Tabs' when format query. 
Please note that choosing 'Tabs' may still result in spaces at the trailing of indent if the tab width and indent don’t match.
3. Added a setting 'Indent Width' to 'Preference - Format Query' to allow users set indent width.
4. Added a setting 'Comma(“,”) that Split Column Definition Style' to allow users set the comma style to 'Leading' or 'Trailing'.

Screenshots attached.
![TextEditing](https://user-images.githubusercontent.com/38027540/81933981-c6674d00-9620-11ea-8e8f-073804d447a8.png)
![FormatQuery](https://user-images.githubusercontent.com/38027540/81933985-c6ffe380-9620-11ea-85f5-f3680c62b7a8.png)

**Comment by SQLiteFlow** [comment]
SQLiteFlow(macOS) 4.0.0 has been released.
